### ISSUE TITLE
“Article continues below”

### ISSUE THREAD

**Issue by beep** [alistapart/AListApart#105]
Per a discussion in Slack, I noticed this reading an article on my phone:

![pasted_image_at_2014_11_25_10_57_am](https://cloud.githubusercontent.com/assets/124493/5186216/fad0d3aa-7492-11e4-9065-0fe658e78269.png)

That “Article continues below” box seemed skip link-ish. (I may have tapped it a couple times.) Just wondering: _should_ this be a link? If not, should we deemphasize it a bit?

(If we wanted to make it a link, we could toss in an empty element with an `id` at the bottom of `.utility-side-bar`. Sorta like we did on [article pages for the BG](http://www.bostonglobe.com/news/nation/2014/11/25/fires-burn-ferguson-gunshots-heard-streets/50uMP2DNsawGh7vd17oiPM/story.html#skip-target-related-box), I guess.)

Anyway, submitted as a question! (cc @mikepick @murtaugh)

**Comment by murtaugh** [comment]
After not having really made a decision on this, the stroke has been used elsewhere (see /events).

I, myself,don't have an issue with the stroke — but IMO the down arrows in the original example are what look like a call to action to me.

@mikepick are you ok with us removing those?

**Comment by michellekondou** [comment]
This was corrected in a new issue so I'm closing it.
