### ISSUE TITLE
Reader email: Padding on "load comments" button

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#106]
Request from a reader: 

> I was viewing your site on my iPhone 4s, Safari, and I think your "load comments" button needs more vertical padding.

**Comment by murtaugh** [comment]
The thing is, part of the time it's not a button, but rather a loading indicator. I'm sure we could re-style it to look like a button though, in the scenarios in which it's meant to be clicked/tapped.

**Comment by michellekondou** [comment]
So, after a little research: there are essentially two button styles (see attached images) one is used for forms and the other one is used for actions like <i>load comments</i> button or <i>back to article</i>. Do you think we should revert to having one style button, the form button? Personally I like the way things are now, meaning the distinction between the two buttons.
![blue-button](https://cloud.githubusercontent.com/assets/1759784/6413644/50567cd4-be9a-11e4-975b-b8a42e363fe4.png)
![red-button](https://cloud.githubusercontent.com/assets/1759784/6413645/505845be-be9a-11e4-9a90-8fb11fbd17f8.png)

/cc @mikepick @murtaugh

**Comment by mikepick** [comment]
Now that I'm seeing the original comment again, I'm inclined to tell the reader to go piss up a rope. 

But anyway, if *we* think this is an issue, let's think it through and decide how we want to proceed. Looking at the screenshot, it seems like maybe we have three states? 

i.e.

1. Load Comments
2. Loading Comments
3. Back to the Post

To me, the logic would be to use the standard button style / class for 1, make 2 a buttonless / notification style, and 3 seems more like a link than a button. But maybe that's too complex. My vote would be to standardize buttons for now so we can cut down on the number of different styles across the site. I'd like to revisit the form and button design at some near future point anyway.

Thoughts?

**Comment by michellekondou** [comment]
Loading comments actually is a different style:

![loading-comments](https://cloud.githubusercontent.com/assets/1759784/6414320/144318ce-be9f-11e4-8a5c-a84d2d40a862.png)

I don't think what Mike is suggesting is too complex, I think it makes sense. What do you think Tim? Shall I go ahead and implement it?

**Comment by murtaugh** [comment]
Sounds good to me.

**Comment by michellekondou** [comment]
Mike, how should the style for the back to post link be? below is how it looks by default (serif and sans).

![link](https://cloud.githubusercontent.com/assets/1759784/6441670/c4cf25d4-c0f2-11e4-9596-c039c691a439.png)
![link-sans](https://cloud.githubusercontent.com/assets/1759784/6441673/cc8bcbc4-c0f2-11e4-86c1-a6d9b790e8ab.png)

/cc @mikepick @murtaugh @aparkening

**Comment by mikepick** [comment]
Why don't we use that rounded grey button style we use for various things around the site (embed, close, etc.). Which I guess is like that Loading Comments notification? Or is that not distinct enough?

**Comment by aparkening** [comment]
It doesn't look bad now.  It's styled like the embed, close, etc., as Mike suggests. http://alistapart.com/comments/container-queries-once-more-unto-the-breach#339346

It looks like we're using a different hover (color change vs. underline) and font style (caps and weight) in a similar button: http://alistapart.com/blog.

@mikepick was suggesting using the dotted outline for focused states in #190, so it may make sense to make the "Back to the Article" button the same as the grey ones in that issue.

@mikepick would you prefer to standardize on the all caps and bold button of http://alistapart.com/blog, or the title caps and normal font weight of http://alistapart.com/comments/container-queries-once-more-unto-the-breach#339346?

**Comment by mikepick** [comment]
I think I would prefer normal weight, mixed case, as a standard. 

Also, we'll need to probably darken the background on all these buttons as per https://github.com/alistapart/AListApart/issues/218

**Comment by aparkening** [comment]
Great, thanks Mike.

**Comment by murtaugh** [comment]
Unless I'm misunderstanding, this button is now standardized with the others to be darker, and mixed case.

**Comment by aparkening** [comment]
@murtaugh: If we're standardizing on mixed case and normal weight, that means that the button at the bottom of http://alistapart.com/blog also needs to be updated to match like http://alistapart.com/comments/container-queries-once-more-unto-the-breach#339346.

**Comment by murtaugh** [comment]
Got it. (It's not showing up on dev because it's in a different branch.)
