### ISSUE TITLE
“Commenting is not available” blurb contains instructions for posting a comment

### ISSUE THREAD

**Issue by beep** [alistapart/AListApart#107]
![](http://cl.ly/image/3t0S0c1H1E0u/Image%202014-12-02%20at%2011.12.25%20PM.png)

Just saw this at the bottom of the comments for [responsive web design](http://alistapart.com/article/responsive-web-design)—if an article’s closed, should we strike the “Got Something to Say? / Discuss this article….” bits?

**Comment by michellekondou** [comment]
This needs to be corrected for the column and blog templates as well, I'll create a new issue.
