### ISSUE TITLE
Authentication Error When Editing "The Basics" Profile Section

### ISSUE THREAD

**Issue by AnthumChris** [alistapart/AListApart#108]
I can login successfully, and I receive an authentication error when I try to change my Visible Name in "The Basics" of the profile edit page.

**Reproduction**
1.  Login
2. Scroll to bottom, click "Edit Your Profile"
3. Change Visible Name Field
4. Enter password Twice
5. Click Submit

After those steps, I receive an error page: "The form you submitted contained the following errors: The password you submitted was not correct"

I'm using the same password I used to logout and login.  Account was originally created from Twitter link

**Comment by operatino** [comment]
I have the same issue, can't change a name and email.

**Comment by michellekondou** [comment]
Issue solved, you need to submit your current password to submit the form.

**Comment by AnthumChris** [comment]
@operatino, @michellekondou: I believe this bug still exists and is not fixed.  Please reproduce by using my test case outlined above.

**Comment by operatino** [comment]
Yup, problem still here, nothing changed.

**Comment by AnthumChris** [comment]
@michellekondou Unfortunately, there's not aforementioned field to enter password to submit the form.  We only have 2 fields to change the password, which don't help us if we wish to make a change that is not related to the password.

![screen shot 2015-02-10 at 1 39 50 pm](https://cloud.githubusercontent.com/assets/10064176/6135999/770e4aaa-b12a-11e4-80af-65fc0f8aed04.png)

**Comment by AnthumChris** [comment]
Please note that step 3 "Change Visible Name Field" must be changed.  If the visible name is not changed, then entering your password in "Password Confirmation" only succeeds.  Changing visible name fails the test.

**Comment by murtaugh** [comment]
Sorry @operatino and @AnthumChris! The fix has not been deployed to production.

**Comment by AnthumChris** [comment]
No worries, thanks for the update.
