### ISSUE TITLE
Pagination links to offset without entries

### ISSUE THREAD

**Issue by sjelfull** [alistapart/AListApart#116]
In some instances, Previous might link to an offset after you have reached the end.

For example: http://alistapart.com/topic/content-strategy/40 is showing the Previous link.

This only happens in some places, like that category and http://alistapart.com/topic/css/120. All the others I've tried hides the link just fine.

**Comment by murtaugh** [comment]
Yes, this was me being lazy during the rush to launch the new site. It's not a bug, per se, since the logic isn't there at all to hide the button where there aren't any more articles :)

**Comment by michellekondou** [comment]
I replaced the PHP in the topic.html template with the EE default pagination tags in the topic-list embed. If we agree on this move, we should replace it on all archive pages.

/cc @murtaugh
