### ISSUE TITLE
Change footer (C) to 2015

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#117]
Pretty much right there in the title. 

![image](https://cloud.githubusercontent.com/assets/3171996/5770989/87713538-9d02-11e4-8ed1-97e5d2b2fb2d.png)

**Comment by michellekondou** [comment]
In the 'global-footer.snip' snippet you could use a date variable and never worry again! 
Copyright © 1998-{current_time format="%Y"}

**Comment by murtaugh** [comment]
Done and done.
