### ISSUE TITLE
Linebreaks disappearing in comments

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#126]
Per [Anne Gibson's tweet](https://twitter.com/kirabug/status/563422560336228354), it looks like linebreaks are being scrubbed from comments on the site. [For example](http://alistapart.com/comments/reframing-accessibility-for-the-web#338576):

![screen shot 2015-02-12 at 10 47 23 am](https://cloud.githubusercontent.com/assets/4195281/6170736/a9d6b91a-b2a4-11e4-90d5-aa0a720c2a2b.png)

Based on a discussion with Tim in Slack, it seems like this may be tied to the EE upgrade a while back.

**Comment by michellekondou** [comment]
I updated this so comments keep the <code>p</code> and <code>br</code> tags. I'm not sure about it though, comments with both <code>p</code> and <code>br</code> tags look a bit all over the place.
