### ISSUE TITLE
Search box doesn't always expand

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#127]
Per [Luke Tully's tweet](https://twitter.com/dansecommander/status/565778384270016512) it seems like the search field isn't expanding when there isn't enough room for the state change.

**Comment by LukeTully** [comment]
I noticed the issue was occurring at about 660px wide on my Mac in Chrome 40. It seems that the state change is reliant on mouseover which could also cause problems.

On click/submit it just shows the HTML validator for required field when the actual input isn't visible.

**Comment by murtaugh** [comment]
This seems to be a media query/viewport size issue. The hover works over 800px, but not under it. I think  at some point we changed the threshold for when the nav reconfigures for smaller screens, but neglected to update the CSS/media query for when :hover triggers expansion and when it doesn't.

There's no JS here, BTW, excepting validation; it's all :hover and :active and :focus for the large screen display. When the nav changes configuration for smaller screens, the search field is no longer hidden, so no expansion is needed.

**Comment by michellekondou** [comment]
Ok, it needed to work over 600px.
