### ISSUE TITLE
Missing character from name headline on author’s profile

### ISSUE THREAD

**Issue by JasonNeel** [alistapart/AListApart#135]
Was perusing the author pages, and stumbled upon [Faruk Ateş’ page](http://alistapart.com/author/farukates). His name inside the `.author-header h1` is being truncated, or to be more specific it seems the Franklin ITC font being loaded doesn’t contain the *ş* character. 

Could the font be subset in a way that this character is loaded from a fallback font?

Screenshot for reference:
![image](https://cloud.githubusercontent.com/assets/1549704/6363721/9b934c04-bc6a-11e4-9ce3-d7f80bb6cfef.png)

**Comment by murtaugh** [comment]
I renewed the font via Webtype's control panel, which seems to have done the trick.
