### ISSUE TITLE
SEO: add canonical link tags to all templates

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#145]

**Comment by michellekondou** [comment]
@murtaugh 
It seems that on archive pages like http://alistapart.com/articles/archives/10 we should implement  rel=”prev” and rel=”next” in conjunction with rel="canonical" (ref.http://googlewebmastercentral.blogspot.gr/2011/09/pagination-with-relnext-and-relprev.html). Does that sound right?

**Comment by murtaugh** [comment]
Yeah, it seems like it would be appropriate to have those.

We'd have to do some PHP work in the `head` to sniff for the "P10" pattern, then deducing which links come before and after.

**Comment by murtaugh** [comment]
Although that solution leaves us with the same problem is before, namely that we can't deduce from the URL whether there's actually more content to link to.

**Comment by michellekondou** [comment]
I think if we use the expressionengine pagination module it may work as expected. I'give it a try.

**Comment by michellekondou** [comment]
@murtaugh  I included rel canonical links in about and topic pages and subpages where I saw they were missing.
