### ISSUE TITLE
SEO: 500 errors on commenting system

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#147]
@michellekondou 500 is fairly unhelpful error, but it's easy to see something's up with textile again:

http://alistapart.com/comments/horizdropdowns/

**Comment by michellekondou** [comment]
The problem was with code in the comments, javascript sanitizing, I corrected this http://alistapart.com/comments/horizdropdowns/ and this http://alistapart.com/comments/dynatext/ (found in webmaster tools)
