### ISSUE TITLE
SEO: 404s.

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#149]
I've pulled the list of 404s into a Google Doc:

https://docs.google.com/spreadsheets/d/1z6umsS4vjAbQqxC5Aq7EC3xW9D1JIByjPO3YVaJ9Yro/edit?usp=sharing

It's intimidating. We will need to go through it to identify specific issues that can be addressed in order to redirect browsers to the right page. 

Of course, there are going to be a large number of 404s that aren't our error (e.g. inappropriately escaped characters or HTML in the linking hrefs) and can't be accommodated for (outside of adopting a more helpful strategy for our 404 page).

**Comment by aparkening** [comment]
Done!  This was such a long list!  Well done @michellekondou!
