### ISSUE TITLE
Where do we talk about being able to clone the EE codebase?

### ISSUE THREAD

**Issue by circa1977** [alistapart/AListApart#15]
I've done a lot of work with ExpressionEngine sites among distributed teams, and noted in the ALA article & README.md here that you're exploring ways to run the site locally. I'd be interested in contributing to that conversation. We got the workflow down to something really easy, but storing EE in a public repo would be a violation of the ToS, too.

**Comment by michellekondou** [comment]
Shouldn't this be closed? /cc @murtaugh
