### ISSUE TITLE
SEO: Fix microformat errors

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#150]
@sarawb: I need more info on this. The hentry microformat validates fine according to Google's validator, but perhaps that's not a good validator, or I'm not validating the right URLs, etc etc.

**Comment by sarawb** [comment]
@murtaugh I'm not sure—this might need to wait til we can get more hands-on help.

**Comment by murtaugh** [comment]
If we could ask Jonathon what he was validating and what he was using to validate it, it would be helpful.

**Comment by murtaugh** [comment]
Relating this to #158

**Comment by murtaugh** [comment]
I found the microformat errors in webmaster tools.

a. the new link post template needs author info
b. the standalone comments template needs author/updated info

**Comment by michellekondou** [comment]
Downloaded the latest csv from webmaster tools and corrected the errors, we should be clean for the next crawl.
