### ISSUE TITLE
SEO: Block URLs like http://alistapart.com/articles/archives/31280

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#153]
These were generated by the archive nav that had incomplete logic. Michelle fixed the nav, but we need to figure out how to make Google forget they existed.

I'm not sure how we can programmatically block them, since one that doesn't exist today may exist tomorrow. A better course might be to use Webmaster Tools to expressly tell Google to forget the bad URLs it knows about.

**Comment by murtaugh** [comment]
"I'm not sure how we can programmatically block them"

Of course, I just realized there's quite an easy way to 404 them via the EE templates. Removing them from Googles index would still be good though.

**Comment by murtaugh** [comment]
updated the archive templates for articles, columns, and blog posts.

**Comment by michellekondou** [comment]
@murtaugh I tested this and I didn't find any mistakes concerning the archive pages. There is another thing though worth looking into, the fact the each channel has different behavior for template group pages, for example:
1) http://alistapart.com/articles/jiberish -> redirects to http://alistapart.com/**article**/jiberish a 404 page
2) http://alistapart.com/columns/jiberish -> redirects to http://alistapart.com/columns
3) http://alistapart.com/blog/jiberish -> redirects to the blog archive 
Consistency wise shouldn't they all behave the same? i.e. either 301 redirect to the next most relevant page like (2) or 404 like (1)?
Should this break into a new issue?

**Comment by murtaugh** [comment]
I think they should all behave like the articles do, no?

**Comment by aparkening** [comment]
As a reader, I'd rather be taken to some useful URL if I click on a bad one, but I don't know whether 404 or 301 is better for SEO/removing bad links from crawls.  @sarawb: any thoughts on whether the behavior should be 301 redirects or 404?

**Comment by sarawb** [comment]
I think these should 404, only because if you type in a bogus URL, a 404 at least tells you, "you typed in a bogus URL," while just sending them to a main page might be confusing. We can 301 when we know what they need, but if it seems they were seeking something specific but we don't know what, 404 gives some context.
