### ISSUE TITLE
SEO: Soft 404s

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#155]
URLs like this one:

http://alistapart.com/topics/userscience/accessibility/

... should either be redirecting to a topic page that exists, or throwing a hard 404.

**Comment by michellekondou** [comment]
@murtaugh  I'm not sure, but do you think these cases should be sending 404's as well? These are not the typical soft 404's reported in webmaster tools, its more a matter of content (meaning if a user hits the URL he doesn't get the expected result).
1) http://alistapart.com/topic/userscience/ (gets the archive templates listing all entries)
2) http://alistapart.com/topics/userscience/ (redirects to alistapart.com/topics)

**Comment by murtaugh** [comment]
That first link should redirect to the second — editors shouldn't be assigning top-level categories. I noticed Rose used a top level for a recent column, but I decided not to make an issue of it since we're hopefully replacing the taxonomy soon.

**Comment by murtaugh** [comment]
Eh, that first link should be 404ing, not sure why it's not, but pushing a fix now.
