### ISSUE TITLE
SEO: Go through our URL parameters list

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#156]
@sarawb: Do you know what our "URL parameters list" is? Is this a webmaster's tools thing, or something else?

**Comment by sarawb** [comment]
Yep: https://support.google.com/webmasters/answer/6080548?hl=en

**Comment by murtaugh** [comment]
It seems to me that setting canonical URLs for all our content will do the trick. We don't have parameters in the way that this describes them — clothing sizes, colors, etc. In our case, I could see a parameter being something like "printable," but we don't use anything like that.

**Comment by murtaugh** [comment]
Going to relate this to #145

**Comment by murtaugh** [comment]
Reviewed the list, flipped appropriates switches for Google's clarification. Also updated robots.txt to disallow `?ACT` URLs.
