### ISSUE TITLE
SEO: generate author URLs with hyphens between first and last names

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#157]
I'm not sure `/author/fname-lname` is possible with the way things are currently set up; however, @michellekondou and I have been working on the idea of migrating author data into a new channel, so we can use "entry" data instead of "user" data for authors, which is more flexible. Once that's in place we can certainly create this new URL scheme.

*But*: Is first & last name sufficiently unique? Even if we make `author/fname-lname` happen (and redirect all the existing ones), what happens when we bring on a second author named John Smith?

We may have to sacrifice some URL purity here, and go for something like `/author/[ID NUMBER]/fname-lname`. @sarawb, does that seem like a reasonable compromise? We lose the clean appearance of the URL, and the "hack-ability" for what that's worth, but seems like SEO should be a higher priority.

**Comment by sarawb** [comment]
I wonder about changing all the existing authoer slugs to a new URL—I _think_ we might just want to leave those, since they have a lot of historical links. 

It'll be rare that we have two people with the same fname-lname; is there something simpler we can do in that case (e.g. just have the system add a 2 to their slug, or throw an error that asks the CMS editor to override the auto URL slug with a unique one?

**Comment by murtaugh** [comment]
If we continue to use the built-in username field (which is fine, even when we add on the new Authors channel), We *could* manually change the usernames for all the authors to be `fname-lname` and enforce that going forward. We'd want to let them know we're doing it, but the extra Google juice would be to both our benefits.

We'd take a slight juice hit for changing the existing page URLs, but my read on this from your post was that it's worth it, but maybe I read into it wrong. It would be easy enough to generate a list of redirects for the existing authors.

**Comment by murtaugh** [comment]
@sarawb: Do you think the small SEO hit we take from redirecting the author URLs is worth installing the new, plain language URL scheme? If not, we will leave them alone. I think it seems worth it, but leave it up to you since you were in the room with the expert, so to speak.

If that's the way we go, here's my proposed plan of action:

1. Install a new custom field for "URL Title" in the Members area. (If we have moved to the new People channel, we can skip this step.) Rather than automatically generating `fname-lame`, we should let the authors define what the URL segment should be. I'm certain EE will screw it up with some names, and better that we publish with what the author wants Google to find.
2. Generate a list of redirects for htaccess.
3. Update all references to author URLs in the templates.

If we *don't* want to change the existing URLs, all we need to do is ensure that all author accounts created going forward are SEO-friendly.

**Comment by sarawb** [comment]
I really do not want to change existing author URLs; can we just change them going forward? We took such a huge hit with /articles/ to /article/. 

I would also like to avoid having people have to enter a field for URLs. I am already struggling to have editors adjust article slugs appropriately. I'm not sure why this is needed?

**Comment by murtaugh** [comment]
If that's the approach you want, no need for the extra field. All we need to do it make sure everyone's username is SEO-friendly from now on.

This will need to be communicated to Erin and/or the editors — I'm not sure who's setting up user accounts for authors.

If a new author already has an account, we should request that they change their username before publishing to be SEO-friendly, if it isn't already.

**Comment by murtaugh** [comment]
Just chatted with @erinlynch, who still handles author accounts as part of the issue process. From now on he will make sure we generate SEO-friendly usernames for authors.
