### ISSUE TITLE
SEO: Add schema.org to the use of microformats, Open Graph, and Twitter Cards

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#158]
@sarawb: I need a little more info on this. What does it mean to "add schema.org"?

**Comment by sarawb** [comment]
The rest of the note from BC: 

> Author snippets won’t show up, but it’s still worth putting the code in place to win trust from google. Looks like publisher markup is already in place.

Remember how we tried to get the author snippets to work? J verified that those won't in the note above, but he's recommending we still use author attribution. And Schema.org has a whole host of schema structured content types, many of which would be relevant to us (e.g. http://schema.org/TechArticle).

**Comment by murtaugh** [comment]
Right. Author snippets worked, sometimes, for a couple months, but then Google removed them.

"add schema.org" just reads like schema.org is one thing; I didn't really know what he was referring to. I guess we should choose the schemes we want?

**Comment by sarawb** [comment]
Yeah, basically, we should add it for anything that makes sense: blog post, tech article, event, etc.

**Comment by murtaugh** [comment]
Ok, so, either Michelle or I or both will dig into Schema.org and see what applies.

After looking at the tech one briefly, we *may* want to add a feature to the editing system that lets an editor apply a specific microformat. There might be times when the template shouldn't assume.

**Comment by murtaugh** [comment]
This might take a little time, since we will:

1. need to identify the schemas we want to use
2. add a setting in EE to let editors pick which schema is appropriate for the article in question
3. update the templates to handle this variable schema.

I might be wrong, but I doubt we can simply apply one schema to all articles/columns/etc. The "tech" schema, for example, is expressly for "step-by-step how-tos", which we rarely do.

**Comment by michellekondou** [comment]
I'm closing this because we are keeping progress notes for adding schemas in issue #240
