### ISSUE TITLE
Header & Footer cuts off

### ISSUE THREAD

**Issue by julienetie** [alistapart/AListApart#161]
I'm not sure if it was intended, I'm on Chrome Linux and the header & footer of the site are cut off. Looks a bit confusing in my opinion. 

Even after adjusting top/ margin-top on .killer-logo & adding bottom/ margin-bottom on .deadly-subtitle via DevTools the logos can still be mistaken as 'poor design' due to the cut-offs. Hope this helps!

**Comment by murtaugh** [comment]
Ha, it's been a while :)

It's a design choice, but thanks for reporting it!

**Comment by julienetie** [comment]
Ah I see, cool no probs ;)
