### ISSUE TITLE
Comment section showing PHP code and profile image not rendering correctly

### ISSUE THREAD

**Issue by xinsnake** [alistapart/AListApart#162]
I was on this link: http://alistapart.com/article/let-links-be-links and I was trying to put a comment (with AListApart account), and it seems that the PHP code is showing directly (ignoring the fact it's using HTTP comment as well, which should be just PHP comment), and the image src is displaying as PHP.

Also it seems that my email is not filled up in the $email variable (I saw it working when I was first redirected to the page, but then later after a refresh it disappeared.

Image attached:

![screen shot 2015-04-01 at 1 21 44 am](https://cloud.githubusercontent.com/assets/1287677/6920987/a9d4ab64-d80d-11e4-978e-bc93df4494d2.png)

**Comment by murtaugh** [comment]
Wow, I wonder how long that snippet has had the wrong settings. I just allowed PHP again for that template, which should clear that up. Thanks for reporting it!
