### ISSUE TITLE
A Mystery Dash

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#163]
A dash has appeared below the comment form:

![screen shot 2015-03-31 at 11 16 38 am](https://cloud.githubusercontent.com/assets/308752/6922296/221fe99c-d798-11e4-88f4-425b3ceb1a16.png)

**Comment by jebaird** [comment]
I think its this file: https://github.com/alistapart/AListApart/blob/dev/default_site/comments.group/embed-comments.html#L36

**Comment by murtaugh** [comment]
Aha! Thanks for finding that!

**Comment by murtaugh** [comment]
Haha — oops, the server seems to be tripping over something. Looking into that :+1:
