### ISSUE TITLE
Events page formatting on medium/small screens

### ISSUE THREAD

**Issue by beep** [alistapart/AListApart#172]
Noticed a couple formatting issues on [the events page](http://alistapart.com/events) at the low end:

![calendar display](http://f.cl.ly/items/2o1W2J0v1c1Z3U2A2s1C/ClouDrop%20Apr%2022,%202015,%208%3A15%3A43%20AM%20Apr%2022,%202015,%208%3A15%3A59%20AM.png)
![avatar baselines](http://f.cl.ly/items/3M3C0L2q3X3P0m2b0h1h/ClouDrop%20Apr%2022,%202015,%208%3A15%3A43%20AM%20Apr%2022,%202015,%208%3A15%3A43%20AM.png)

**Comment by sarawb** [comment]
Yikes. 

When fixing, can someone also un-capitalize Author on Susan's bio snippet, please?

**Comment by aparkening** [comment]
"Author" caps was fixed, as was the vertical position of text beside the participant photo (at least on my screens).

Still seeing odd indents and spacing in smaller breakpoints.  Similar screenshot to Ethan's:
![screen shot 2015-05-31 at 3 48 34 pm](https://cloud.githubusercontent.com/assets/7241111/7903514/eb281ca8-07ac-11e5-9913-c49d9ffdd874.png)

Any reason not to just center-align these items, as they are in the larger breakpoints?

**Comment by murtaugh** [comment]
Deployed a fix for this on dev.

**Comment by aparkening** [comment]
Ah, not fixed for smaller sizes, @murtaugh ?

Still seeing this on Dev:
![rwd-text](https://cloud.githubusercontent.com/assets/7241111/8161213/6cd3a4e2-1343-11e5-9e8d-11f44a289838.png)

**Comment by aparkening** [comment]
Any reason not to adjust the layout for full width container in smaller sizes?

![rwd-left-container](https://cloud.githubusercontent.com/assets/7241111/8161272/ce2a789c-1343-11e5-84cc-bf543149ad68.png)

**Comment by murtaugh** [comment]
Oh, dev is not pointing at the branch I thought it was, so the fix isn’t there yet.

**Comment by murtaugh** [comment]
Dev is updated with this fix now

**Comment by aparkening** [comment]
This looks great!  Thanks Tim.

**Comment by aparkening** [comment]
@beep: feel free to ping http://dev.alistapart.com/events and let us know if you have additional thoughts. 

Otherwise, @murtaugh I think this is good for testing on core devices/browsers and deployment.

**Comment by beep** [comment]
@aparkening Just took a quick look on Firefox, and it looks stellar!
