### ISSUE TITLE
Standardize format for the domain variable

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#174]
I've not sure what the domain variable is at the moment, but in the Mailchimp emails we're getting a double slash:

http://alistapart.com//column/why

We should standardize the domain variables on our platforms to *not* have the slash, as I will always want to format the rest of the URL with an absolute slash to root. :)

**Comment by murtaugh** [comment]
Dupe bug.

**Comment by michellekondou** [comment]
@murtaugh I changed the config variable to not use a slash and replaced all instances of the site_url variable in the templates - it should be ok, just noting this here in case we bump into weird behavior
