### ISSUE TITLE
Create relationships between Article, Blog, and Column posts

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#179]
Scenarios:
1. This is content is old; go see this new thing that is better. Position: top 
2. This is the first part of a series of related things; go see the next thing. Position: bottom 
3. This is a continuing part of a series; go see the first one. Position: top

Vision: editor creates the relationship once and it puts #2 on the older item and #3 on the newer item.

**Comment by murtaugh** [comment]
Here's more detail and some questions: (cc: @sarawb)

1. A new field that allows editors to select a piece of older content that the new entry is "replacing." On the front end, the new entry is called out at the top of the older entry, with automated messaging, something like: "While great for its time, this article is now out of date. Learn more here: [Article Title]"

(All my copy is FPO, obv)

2 & 3. A mechanism that allows editors to define a "series." We could add a relationship field, which the editor uses to assign an entry's predecessor. We infer the order by publish date. This is a simple solution from a workflow perspective, but the templating logic for this comes with a bit of processing overhead that might become a problem if we ever want to list a long chain of articles.

We could build a slightly more complex mechanism to formalize groups of entries, for example by creating a non-public set of categories or tags. This would allows us to name the groups, and would allow us to automatically generate something like this in articles:

> This article is the [count] in a series on [topic]. Here are the rest: link, link, link

Does that make sense?

Question: Is there a reason not to build both of these into all content types? (excepting Events) Obviously we have way more articles that will "go bad," so to speak, but I can think of at least one blog post that needs an update.

**Comment by aparkening** [comment]
If we could make it as simple as possible on the workflow end, then I don’t see a problem with adding both methods to each content type.  You're already doing the work for Article, so unless it would add lots of programming overhead to implement in Blog and Column, I think this is a good idea.

**Comment by murtaugh** [comment]
Sorry to open this back up again, but:

Do any of these mechanisms address the "blog post as follow up to article" scenario? Are we overthinking the whole "series" aspect of things?

The example that comes to mind are two posts on our pattern library:

1. http://alistapart.com/blog/post/getting-started-with-pattern-libraries
2. http://alistapart.com/blog/post/pattern-library-security-vulnerability

The second post doesn't deprecate the first one, but neither does it create a "series" in the way we've been discussing it. (cc: @sarawb)

**Comment by aparkening** [comment]
Front-end scenarios look like:
1. A notice at the top that this content is old, replaced by this newer piece.
2. A notice at the top that says this content is part of a series, with links to the others. (A series is decided by the editor – a piece that they believe is very closely related, that they believe should be read before or after this piece).
3. Links & short decks below the main post that show editor-selected related pieces.

Anything more complicated than that, and the author or editor could simply include links inside the post itself.

**Comment by aparkening** [comment]
Relevant to this effort: as a follow-up to Matt Griffin's 2nd post in a series, a Twitter user asked if there was a way to view other items in this series: https://twitter.com/iamdereklong/status/598217139477151744.

**Comment by michellekondou** [comment]
After some research, I see that we already have a field that sort of covers scenarios 1 and 2. There is the Opening Editor's Note field that has already been used in a) 6 cases to denote a Series / Follow up entry and in b) 20 cases to denote that an article is outdated, referencing a link in two cases (external in one case and internal in the other). 
Here is the link to a spreadsheet with all the data I queried from our DB (https://docs.google.com/spreadsheets/d/1qvy1aTJhI_zhURYdAWzVSPlRdB8rbeeotF16fwTlBfo/edit?usp=sharing). It contains all the entries with an Opening Editor's Note (entry_id, editors note content and type).
So do we need a new field for this or do we just need to modify the existing field and if yes in what way?
Also in the spirit of cleaning up in the Control Panel, there is a field that flags an article as outdated, but I see that is has only been used in 16 cases (and not in all the cases where an article has an outdated editor's note) so we probably do not even need it, am I right?

**Comment by murtaugh** [comment]
@michellekondou: can you see if that flag has been used in any templates? I don't think it has, I think it was an aspirational field that we hoped we'd get to.

The editor's not field isn't sufficient for this, because we want to create formal relationships with the data, not just put up notes.

**Comment by michellekondou** [comment]
@murtaugh: Yes ofcourse that makes total sense, so we can port existing cases that are using the editor's note for those two scenarios over to the new fields.

**Comment by michellekondou** [comment]
@aparkening @murtaugh @sarawb 

Scenarios & links on DEV with implemented versions. In all the examples I have left the old editor's note - where there is one - in place for style comparison.

1. A notice at the top that this content is old, replaced by this newer piece.
(http://dev.alistapart.com/article/supereasyblendys)

2. A notice at the top that says this content is part of a series, with links to the others. 
http://dev.alistapart.com/article/publication-standards-part-1-the-fragmented-present

3. Links & short decks below the main post that show editor-selected related pieces.
http://dev.alistapart.com/article/meta-moments-thoughtfulness-by-design

4. Follow-up blog post to article
http://dev.alistapart.com/article/meta-moments-thoughtfulness-by-design

**Comment by michellekondou** [comment]
@aparkening @murtaugh @sarawb

For scenarios 3 and 4 I followed the new article template style so links and short decks are placed in the sidebar (it is by no means complete, there are different things I need to discuss with Tim and Mike concerning structure and style, but I thought it would be a good idea to start the new template for the related content widget).
