### ISSUE TITLE
Image subdomain redirects incorrectly

### ISSUE THREAD

**Issue by yorkshiretwist** [alistapart/AListApart#180]
Subdomains for images are not redirecting correctly. For example see the images on http://alistapart.com/article/art-direction-and-design

Unfortunately I can't see the source of the page on my mobile device, but from memory the images are on d.alistapart.com but requests to this subdomain get redirected to alistapart.com/d/d. There should be just one /d.

**Comment by murtaugh** [comment]
This has been cleared up, thanks for the report. :+1:
