### ISSUE TITLE
Dark Corners: design: background image (arrow top left) in form needs to be a tone darker to match border

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#187]

**Comment by aparkening** [comment]
@michellekondou: Are you referring to the top left arrow on the comment login form (screenshot below), for example?
<img width="285" alt="login-arrow" src="https://cloud.githubusercontent.com/assets/7241111/8581561/9125187c-258f-11e5-9a32-27c4217a482a.png">

**Comment by aparkening** [comment]
As discussed, this is very small, and we'll probably change it in future designs.
