### ISSUE TITLE
Dark Corners: register process 

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#188]
Enhancements:
1) after I submit the registration form I need to be notified that I will receive a member activation email
2) include a warning to check the spam folder in the activation notice, include a list apart in the safe senders list

**Comment by michellekondou** [comment]
Tim has included the notice. @murtaugh - I don't think we need to include the spam folder notice, if you agree I'll close this.

**Comment by murtaugh** [comment]
I agree.
