### ISSUE TITLE
Dark Corners: design: consistent UI pattern / styleguide for all forms and form elements

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#189]
Forms:
1) login (and twitter + facebooks sign in buttons)
2) register
3) edit profile
4) forgot password

**Comment by mikepick** [comment]
Got it, let me give this a little thought. I'm not crazy about any of these styles really.

The big form fields will make the profile edit page kind of crazy big, that page could use some organization.

**Comment by mikepick** [comment]
I think, as a consistent style, I'd like to propose something like the attached.

![ala_login-form](https://cloud.githubusercontent.com/assets/3209136/8753789/7d56bbc6-2c8c-11e5-806b-6bfdef9dd6a6.jpg)

- all elements aligned left
- all fields and buttons normal weight
- labels 14px
- fields 18px, border 1px #cccccc, border-radius 3px
- buttons 18px, border-radius %50
- primary button red with white type
- secondary button white with #222222 type, #cccccc border
- instructions #666666, italic, 14px

That should cover us for inputs, textfields, and buttons. Do we use other elements elsewhere?

**Comment by michellekondou** [comment]
Hi Mike! Is letter-spacing: 0? Input letter-spacing is set at .1em at the moment in the comment form,  but it seems like 0 in the picture you've attached.

**Comment by mikepick** [comment]
Yes, it's set at 0 in the mockup. I don't know a reason why form elements would need increased letter-spacing. Thanks Michelle!

**Comment by michellekondou** [comment]
@aparkening 
For the following templates, I have:
1) edited the HTML for all templates to use consistent markup (tags and logic) and style 
2) applied accessibility enhancements
3) added honeepot captcha to all the forms
4) edited the css files:  
a. removed editables.css and merged with style.css (in progress)
b. started grouping all form css together to facilitate future file break-up.

dev.alistapart.com/edit/profile
dev.alistapart.com/tools/log-in
dev.alistapart.com/tools/register
dev.alistapart.com/tools/forgot-password
http://dev.alistapart.com/tools/translations/performance-showing-versus-telling
http://dev.alistapart.com/tools/column-translations/job-hunting-for-web-designers-and-developers

@murtaugh @mikepick issues to consider: 
1. Main column width - I've left it to be the full column width of the single column page layout, but it seems very wide and the fields seem really long, should we reduce it for resolutions above 600px wide?
2. General styles, headings, font-sizes, spaces, margins

**Comment by murtaugh** [comment]
+1 to making the forms narrower. i strongly dislike wide fields.

**Comment by murtaugh** [comment]
Minor note:  there was a readonly style for the username field that didn't get replaced. I think at the very least the text in that field should be italic, and perhaps the field greyed out a bit. @mikepick might have thoughts.

**Comment by michellekondou** [comment]
@mikepick I pointed DEV to the form-ui branch again, you are now able to see the changes

**Comment by michellekondou** [comment]
@murtaugh I restored the css for the readonly fields - I need to go through the whole editables.css file in more detail and see what else may need restoring.
@mikepick @murtaugh I made the forms narrower, what do you think? 
Are these changes ready for deployment to production?

**Comment by aparkening** [comment]
Very minor UI bug: the textarea is a larger width than the grey area below it on larger screens in Firefox 39/Yosemite.
<img width="635" alt="screen shot 2015-09-21 at 3 58 28 pm" src="https://cloud.githubusercontent.com/assets/7241111/10003329/d3da76d8-6079-11e5-81da-4870133d373b.png">

**Comment by aparkening** [comment]
Minor button spacing bug: the profile submit buttons run into the form fields and the footer.
<img width="435" alt="screen shot 2015-09-21 at 4 08 06 pm" src="https://cloud.githubusercontent.com/assets/7241111/10003624/52d1d3c2-607b-11e5-9886-2462f369cdff.png">
<img width="329" alt="screen shot 2015-09-21 at 4 11 00 pm" src="https://cloud.githubusercontent.com/assets/7241111/10003632/689efa90-607b-11e5-8318-c4790ead5fbe.png">

**Comment by aparkening** [comment]
Refresh and back buttons work well!

**Comment by michellekondou** [comment]
I've corrected these, I think we can close this issue!
