### ISSUE TITLE
Dark Corners: design: consistent UI pattern / styleguide for buttons and links

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#190]

**Comment by aparkening** [comment]
Andrew had similar thoughts regarding focus, unfocus, and hover states across the site. I've attached an image with his specific thoughts.
![buttons](https://cloud.githubusercontent.com/assets/7241111/7903577/0ba1336e-07af-11e5-8fd4-7a296b0b5ceb.png)

**Comment by mikepick** [comment]
Are the embed buttons part of the contrast issues as well?

**Comment by mikepick** [comment]
For the sake of simplicity, can we make the focus state for all these elements the dotted outline that we seem to be using for everything else?

FWIW, the dotted outline appears to be present on the Issue Badge, but it's white, so it's not always visible unless there is an image behind it.

Also, can we just make the Close button above the same as the Embed button, to eliminate at least one random style.

**Comment by aparkening** [comment]
Yes, the embed buttons in #218 are also part of the contrast issues.

I think making the focus state dotted, and therefore consistent with everything else, is great.

+1 to removing random style, making the Close button look like the Embed button.

Once you've weighed in on all the items, I'll turn this issue over to Tim and Michelle for implementation.

**Comment by aparkening** [comment]
@mikepick and @murtaugh: Does the issue number still underline on focused state for you?

@mikepick: Are you saying you think we should have the focused state for the HC logo as dotted outline, as well?

**Comment by mikepick** [comment]
The issue badge still underlines on focus for me, but to be more plain maybe, the badge does have an outline, but it needs to be a visible color and not white. It seems to me that ideally it would have the dark grey (or black, or whatever the general outline color is) and not underline on focus.

re: HC logo, yes. Let's use the same dotted dark outline for those as well.

**Comment by murtaugh** [comment]
I've consolidated some buttons styles, and added focus states for the elements mentioned here that didn't have them.

**Comment by murtaugh** [comment]
Please feel free to re-open if there are more things to update.
