### ISSUE TITLE
Dark Corners: design: email notification templates

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#191]
1) customize design (typography, simple html, ALA logo/branding, footer details)
2) customize copy (user greeting + message)

**Comment by murtaugh** [comment]
We shouldn't do to much to these — ALA *generally* holds the position that HTML emails aren't preferable.

**Comment by sarawb** [comment]
I think we should absolutely review copy just like we would any email. I'd suggest that a VERY simple and modest amount of HTML that is in line with what we do in the new content alerts (but more stripped down) makes sense. All our emails should be following the same system/be in the same family, I think.

Can someone collect screenshots of or at least copy for all the triggered email responses that exist right now? I am happy to give copy updates but it'd save me a million hours if I don't have to hunt for what those triggers are :)

**Comment by michellekondou** [comment]
Thank you for the reply Sara, I'll collect the screenshots!

**Comment by aparkening** [comment]
@litherland's notes on the emails are in https://docs.google.com/document/d/1QDuZUjKyLCWgX0dj6olp89UDt94RBdPBhBOdCYJCZ6Y/edit.
