### ISSUE TITLE
Re-visit FB login

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#194]
I saw a message that FB is deprecating our app, which lets people log in to ALA using FB — I think all we need to do is set up a new one.

**Comment by aparkening** [comment]
Are enough people using our FB app to log in now that it's worth making another one?
If so, how long will it take (a day, a week, a month)?

**Comment by michellekondou** [comment]
I took some steps
1. created a new FB app
2. used JS to remove the fragment #_=_ that facebook adds to the redirect_uri

@murtaugh I suspect that updating to the latest version may take care of the hash
