### ISSUE TITLE
QA Website on Nexus 5

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#197]
What does the ALA website look like in a Nexus 5 device?  Are there any bugs?

As submitted in Facebook: "Your site looks awful on a Nexus 5. I really wasn't expecting that." https://www.facebook.com/alistapart/posts/10152780642023038?comment_id=10152780964938038&offset=0&total_comments=1&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by awkawk** [comment]
I took a quick look on a Nexus 7 and the only immediate things that one might be concerned with are the top and bottom images, which some people already complain aren't fully visible, and the part where the ads are inserted.  That part does get narrow on the 7 and might be worth a look on a 5 emulator.

Would be nice to get more info from the commenter to determine if this is a user preference or a less subjective issue.

![screenshot_2015-05-11-09-51-17](https://cloud.githubusercontent.com/assets/4228257/7566292/ee9170a4-f7c3-11e4-8b59-151586868e11.png)
![screenshot_2015-05-11-09-51-59](https://cloud.githubusercontent.com/assets/4228257/7566294/ee92faa0-f7c3-11e4-913d-d094c2a1def6.png)
![screenshot_2015-05-11-09-52-22](https://cloud.githubusercontent.com/assets/4228257/7566293/ee92c8aa-f7c3-11e4-9379-7ccfb54242f3.png)
