### ISSUE TITLE
“This post is scheduled” line missing in previews?

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#199]
Looking through a blog post for tomorrow and realized the preview copy we used to have (“This post is in the queue but has not yet been published” etc.) doesn't seem to be showing up on the blog now. Feel free to ping me on Slack for links if that's helpful!

**Comment by marieconnelly** [comment]
So, noticed something odd with this—I was able to see the message on a preview of a post when it _hadn't_ been scheduled and set to "open," but once the post was scheduled, the message seemed to have disappeared. The message that used to say something like "this post is in the queue but has not yet been published," isn't appearing on blog posts currently in the queue.

**Comment by aparkening** [comment]
Thanks for the update, Michelle. Do you need any help testing various
scenarios, or do you have some ideas on how to proceed?

**Comment by murtaugh** [comment]
We have a fix for this, I think it just didn’t make it out to all the affected templates.

**Comment by michellekondou** [comment]
No I have an idea how to proceed with this I will test it tomorrow.
