### ISSUE TITLE
Why is this url 404? http://alistapart.com/author/markhuot

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#202]
He's on the author list, so he's in the system.

**Comment by murtaugh** [comment]
Maybe or maybe not relevant: His is the first member account, and has the lowest ID number.

I changed him from Member to Author, I put in his first and last names and added a bio, but that didn't make a difference.

**Comment by michellekondou** [comment]
It is because there were two records in the DB with the username markhuot (username should be a unique value). Probably one of the two got ported in from some migration. I changed the username for the second record to markhuot1 and it worked. We should merge them and delete one of the two.

**Comment by murtaugh** [comment]
Nice one.
