### ISSUE TITLE
Columns landing page not pulling correct reverse-chron columns

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#205]
On http://alistapart.com/columns, we should have the most recent column featured, followed by reverse-chron listings of the most recent posts by each of our columnists. However, several are not appearing right now: 

![image](https://cloud.githubusercontent.com/assets/3171996/7637252/d119f4dc-fa6c-11e4-879f-34eda448926a.png)

It jumps from Rachel's column (published today) back to March with Laura. Nishant, Rian, and Lyza should be before Laura here. 

The columns archive shows everything.

**Comment by murtaugh** [comment]
There's an additional field that needs to be filled out that hasn't been for the past half dozen or so columns. I just updated those columns and reminded Rose about it.
