### ISSUE TITLE
Fix spacing between entries under "MORE FROM THIS AUTHOR" 

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#209]
![screen shot 2015-05-20 at 11 41 42 am](https://cloud.githubusercontent.com/assets/2983799/7730069/2a06e15e-fee6-11e4-9141-c4baadd4ac45.png)

On ARTICLE page template, where previous articles by the author are listed below author bio, there is no space between them: the comma delimiting one entry touches the first letter of the next entry, and so on.

**Comment by michellekondou** [comment]
The space was being truncated from the css content property upon minification so I added an escaped unicode space instead.
