### ISSUE TITLE
Member rating field showing up in email preferences form

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#212]
Per [Stephen](https://twitter.com/smekosh/status/603616375769300992), on Twitter, "Signed up! Then clicked "Manage My Preferences" and could edit my MEMBER_RATING. Probably an error?"

Stephen's shared a screenshot on Twitter.

**Comment by murtaugh** [comment]
That's a Mailchimp-managed form, perhaps they had a derp of some kind. I'm not seeing it.

**Comment by aparkening** [comment]
I went through the full process and wasn't able to reproduce, either.  I'll close this for now.

@marieconnelly, please let us know if you see any further reports of behavior like this.
