### ISSUE TITLE
Unable to login to comments via Twitter

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#213]
From Kevin, on [Twitter](https://twitter.com/KevinLozandier/status/604672305843814400): 

> FYI: Being able to log-in via Twitter to write a comment doesn't work; on Safari & Chrome, I'm redirected to a blank page…

> Also the /login-return handler seems to be broken if you an alternate log-in method… https://twitter.com/KevinLozandier/status/604673183036370944/photo/1

**Comment by michellekondou** [comment]
@murtaugh @marieconnelly 
We need to update the module that handles the twitter login for the latest EE version. I think the error will be fixed after the update.

**Comment by marieconnelly** [comment]
@michellekondou got it—thanks for the update!

**Comment by michellekondou** [comment]
The module update took care of the error - twitter login is working again.
