### ISSUE TITLE
Accessibility: Improve comment form keyboard tabbing

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#219]
From Andrew's accessibility audit:

- Before the user clicks on one of the three account type buttons, there are invisible tab stops, and after the three buttons there are invisible tab stops. This is because the form is hidden only visually, but the controls are focusable and can be read by assistive technologies.

.article-comments #login-buttons, .article-comments form#sign-in-form, .article-comments form#register-form, .article-comments form#forgot_password_form {
    *** max-height: 0px;
   *** overflow: hidden;
    transition: max-height 400ms ease-in 0s;
}

- To tab through the entire page, a user needs to tab through every form control on the page, even those that are hidden, and this may be as many as eleven tab stops where the focus is not visible.  

- Users who tab to the ALA account button and activate it then need to tab backwards to get to the relevant controls, but because the focus is not visible few users will be able to figure out what to do.

**Comment by michellekondou** [comment]
@aparkening - The changes we made to the commenting and sign in process have solved these issues, would you like to double check before I close this?

**Comment by aparkening** [comment]
@michellekondou: let's deploy and then ask Andrew to check it out.
