### ISSUE TITLE
Accessibility: Make comment error messages more specific

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#221]
From Andrew's Accessibility audit:

Comments log-in error messages make the focus move to the first affected control, which is good.  Error messages could be a bit more specific – e.g. “please provide a username” instead of “please fill out this field”.

**Comment by murtaugh** [comment]
We have all new validation in place, with nice new error messages.

I am closing this bug for now, but I would love @awkawk's input as to whether or not my efforts to make them accessible had any effect.

**Comment by awkawk** [comment]
The messages are fine, but now there is a problem (it may have existed before) where the user may not realize that anything has changed when the validation message appears.  

I only have a mac with me right now but with VoiceOver running when I hit enter to submit the sign in form with the password empty the validation message appears but nothing is voiced.  I think that if the focus was moved to the first field with an issue then it would get spoken correctly.

**Comment by murtaugh** [comment]
Hm, I guess I thought `role=alert` would hadn’t that, but I guess not. I can use JS to put the focus on the first invalid field.

**Comment by murtaugh** [comment]
I've updated the JS on dev so it focuses on the first invalid field.

**Comment by murtaugh** [comment]
VoiceOver still doesn't seem to be reading the error.
