### ISSUE TITLE
Accessibility: Create consistent Events registration labels

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#223]
From Andrew's accessibility audit (not sure if we're still doing the Events registration the same way as when Andrew took a look):

On the events page labels for registration checkboxes should be labeled consistently.  Some controls use for/id, others wrap the input controls with the label element.

**Comment by murtaugh** [comment]
@awkawk the checkbox markup looks consistent to me. can you show me what you mean?

**Comment by awkawk** [comment]
Agree that it looks good now.  Closing as no longer an issue.
