### ISSUE TITLE
Accessibility: Update instances of the old Youtube player

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#225]
From Andrew's accessibility audit:

When using a YouTube player, the HTML version of the player is more accessible, so if possible to force use of that there is a benefit for accessibility. 

Example: http://alistapart.com/event/designing-for-performance

**Comment by murtaugh** [comment]
This is a note for the editors, or more properly Aaron. I'll let him know to keep an eye our for the Flash player.

**Comment by aparkening** [comment]
@murtaugh: did you switch out the player on http://alistapart.com/event/designing-for-performance?  I believe I forgot to include the URL from Andrew's audit.

**Comment by aparkening** [comment]
@awkawk: When I look at YouTube's embed options, I only see one type of embed code, which is based on an iframe (and I assume is HTML-based).  Am I missing something?

**Comment by murtaugh** [comment]
I'm guessing some of our older content still calls the flash player. Maybe @erinlynch would be interested in taking on the task of swapping these out?

**Comment by erinlynch** [comment]
Yes, I can get that into my schedule to look at next week. Do we have a list of articles this needs to be changed on?

**Comment by murtaugh** [comment]
I think if you search entries for "application/x-shockwave-flash" you should find them. There aren't many.

**Comment by murtaugh** [comment]
Assigned to @erinlynch — thanks!

**Comment by awkawk** [comment]
I think Tim has this right - the youtube demo (https://developers.google.com/youtube/youtube_player_demo) says that the Flash and JS embed code was deprecated and provides links to the current embed code suggestions, which will give the HTML player whenever possible.

**Comment by aparkening** [comment]
@erinlynch: are there still posts that need updated Youtube players?  If so, anything you need from us to help?

**Comment by erinlynch** [comment]
Hey Aaron. I still have a few to update. It fell off my radar. Sorry. I’ll get that wrapped up this week.

**Comment by aparkening** [comment]
@erinlynch: Any update on these?

**Comment by aparkening** [comment]
From Erin: I did a check on “<embed” “swf” “shockwave” and a few other terms that were commonly used in the Flash embed. I’m not finding anything else. I’m fairly sure I’ve gotten everything.

**Comment by mcdado** [comment]
For one, this post still has old-style flash embeds: http://alistapart.com/article/inline-validation-in-web-forms
