### ISSUE TITLE
Accessibility: Use HTML data tables in Articles

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#227]
From Andrew's accessibility audit:

Articles need to demonstrate best practices.  The data table screenshots in Issue 418 really should be HTML data tables, or they need much more robust description, probably via longdesc.

**Comment by murtaugh** [comment]
I think this was an editorial call, since the tables in this issue aren't our data, they're examples of 3rd party data.

That said, there are a some other places we've used image tables recently, but we've brought that up with the editors and they know not to do it any longer.
