### ISSUE TITLE
Exempt `code` from auto-formatting

### ISSUE THREAD

**Issue by beep** [alistapart/AListApart#229]
This came up on Jeff Lembeck’s [recent blog entry](http://alistapart.com/blog/post/picturefill-upgrade/), where `<code>npm update --save picturefill</code>` was being displayed `npm update—save picturefill`: in other words, the `--` was being converted to an em dash (`—`).

@michellekondou suggested wrapping the code in a `pre` element, which definitely works. But it seems like we’d want to exempt `code` elements—i.e., inline snippets—from any punctuation conversion. Is that doable?

**Comment by murtaugh** [comment]
This is something that's been filed as a bug with Ellis for a few years now. Maybe we should file another one.

**Comment by beep** [comment]
Just did a quick search, and yeah—it seems like a common issue. Couple SE threads:

http://expressionengine.stackexchange.com/questions/972/how-can-i-display-a-code-example-html-plus-ee-tags-in-my-blog-post <http://expressionengine.stackexchange.com/questions/972/how-can-i-display-a-code-example-html-plus-ee-tags-in-my-blog-post>
http://expressionengine.stackexchange.com/questions/12236/how-to-stop-ee-from-converting-straight-quotes-to-html-entities-in-script-tags <http://expressionengine.stackexchange.com/questions/12236/how-to-stop-ee-from-converting-straight-quotes-to-html-entities-in-script-tags>

Anyway, filing those here in case they’re at all helpful.

**Comment by murtaugh** [comment]
We're going to submit another report to Ellis, as well as see fi we can offer them a fix.

**Comment by michellekondou** [comment]
@beep @murtaugh I don't think these cases are bugs, they are choices made by EllisLab for security reasons. I have a fix to exempt the <code> tag from auto-formatting for specific cases (two spaces into entities, double dashes into em-dashes, three dots into ellipsis, single and double quotes into correctly facing curly quote entities), I'll apply it to DEV so we can snoop around for bugs before pushing it to production.

**Comment by beep** [comment]
That sounds amazing, @michellekondou—can’t wait to see the fix!
