### ISSUE TITLE
Mobile content view on blog posts

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#231]
Stephen Hay reported that the content below "content continues below" isn't appearing-- see tweet: https://twitter.com/stephenhay/status/605603975539400704. 

I also noticed that because we  don't have a featured first graf in blog posts, we don't have any content that appears before the sponsor block. So the article never really starts before we tell readers it continues :) 

Think we could add lead grafs to blog post layouts too?

**Comment by sarawb** [comment]
Ps: here's what I see for blog posts on mobile: 

![image1](https://cloud.githubusercontent.com/assets/3171996/7935490/6da38926-08ff-11e5-9b14-8bce9638f7ff.png)

**Comment by murtaugh** [comment]
FWIW, this isn't an unusual pattern, but that doesn't mean we have to live with it.

**Comment by murtaugh** [comment]
Wait sorry, just *actually* read the report and realized the issue isn't the pattern, but content not showing up, *je suis l'idiot*.

**Comment by murtaugh** [comment]
It looks like The Deck ad didn't load, which, because they haven't provided us an asynchronously loading script (and we haven't gone and made one for them), blocks the rest of the page.
