### ISSUE TITLE
Raw Textile in comments?

### ISSUE THREAD

**Issue by beep** [alistapart/AListApart#233]
Just noticed a few old comments that have raw Textile in them:

http://alistapart.com/comments/responsive-web-design#328887
http://alistapart.com/comments/responsive-web-design#328902
http://alistapart.com/comments/responsive-web-design#328903
http://alistapart.com/comments/responsive-web-design#328910

Is this fixable?

**Comment by murtaugh** [comment]
This is mentioned in another issue: #147 

I think @michellekondou has thoughts on it, but we haven't been able to get to it.

**Comment by aparkening** [comment]
@michellekondou: was this solved when you closed #147 ?

**Comment by michellekondou** [comment]
No, this is a different issue.

**Comment by aparkening** [comment]
As discussed in Slack, this looks like it was caused by moving from EE1 to EE2. Tim will manually fix this set of comments and open up a larger issue if we encounter other textile snippets.

**Comment by murtaugh** [comment]
I've updated the comments in this thread. It's still on our list to find a comprehensive fix.
