### ISSUE TITLE
No TLS/HTTPS on alistapart.com

### ISSUE THREAD

**Issue by slightlyoff** [alistapart/AListApart#237]
It seems the site is served over insecure transport. Given that major browsers intend to [begin marking](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure) HTTP as insecure and have stated that [HTTP is being deprecated](https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/), ALA's leadership would be meaningful and timely.

I understand that rolling out TLS on a major site can sometimes be a hassle, so the admins may be happy to hear that a [new feature to ease this transition](https://w3c.github.io/webappsec/specs/upgrade/) recently [shipped in Chrome](http://blog.chromium.org/2015/04/chrome-43-beta-web-midi-and-upgrading.html) and [is being implemented in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1139297).

**Comment by aparkening** [comment]
Thanks for the nudge, @slightlyoff. We've got a bunch of accessibility issues we're prioritizing first, and we've added TLS/HTTPS to our list of projects for the summer.

**Comment by slightlyoff** [comment]
Excited to hear it! Would also love to see an ALA article about the journey; I'm guessing it'll be an experience soon to be shared by many.

**Comment by zeldman** [comment]
Yes, it should have been closed four years ago.  :)
