### ISSUE TITLE
SEO: Possible schemas to apply to content templates

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#240]
http://schema.org/Article
http://schema.org/TechArticle (I think this will rarely apply, actually)
http://schema.org/ScholarlyArticle (not sure how Scholarly is defined)
http://schema.org/BlogPosting
http://schema.org/Comment
http://schema.org/PublicationIssue
http://schema.org/AboutPage
http://schema.org/ContactPage
http://schema.org/ProfilePage
http://schema.org/SearchResultsPage (not sure if it's possible to apply this to Google Custom Search, or if it's needed)
http://schema.org/BroadcastEvent

**Comment by murtaugh** [comment]
This is in regard to #158

**Comment by michellekondou** [comment]
@murtaugh 
I've started with the article template.

**Comment by michellekondou** [comment]
Added schema's to the blog and column post templates.

**Comment by michellekondou** [comment]
Added schemas sitewide to elements in body, header, navigation, footer, to about, contact and search results templates

**Comment by michellekondou** [comment]
Added BroadcastEvent and ProfilePage
