### ISSUE TITLE
Apostrophe isn't displaying properly in RSS

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#241]
I'm having a hard time getting this to display in Feedly at all, but when I preview from [the RSS page](http://alistapart.com/about/rss) I'm seeing:

![screen shot 2015-06-17 at 3 24 25 pm](https://cloud.githubusercontent.com/assets/4195281/8216619/a594b2da-1505-11e5-9437-4da0a1f54387.png)

I _think_ this was a plain apostrophe mark (vs a curly one) and have updated the EE entry to make sure, but it's still showing up this way. Not sure if there's some refresh that needs to be sent out on our end somehow?

**Comment by murtaugh** [comment]
How about now?

**Comment by marieconnelly** [comment]
Hmm, still showing up that way for me. Tried it in a new browser to make sure I wasn't hitting any cache issues on my end.

**Comment by murtaugh** [comment]
What reader?

**Comment by murtaugh** [comment]
Wait I forgot to kick Feedburner after I made the change, try again.

**Comment by marieconnelly** [comment]
Yay! thanks, Tim!
