### ISSUE TITLE
Is the Picturefill Script Current

### ISSUE THREAD

**Issue by erinlynch** [alistapart/AListApart#242]
I talked with Tim during production on 422 about this issue. 

I placed hi-dpi images into Johanna Bates' article, The Homepage Exception (http://alistapart.com/article/homepage-exception), but they were still rendering in what appeared to be low res. Tim took a look and asked me to submit an issue on it. We were both wondering if the Picturefill script might be out of date, making hi-dpi images not render when they should.

**Comment by Wilto** [comment]
Ref. #254
