### ISSUE TITLE
Changing email is password-restricted

### ISSUE THREAD

**Issue by jefflembeck** [alistapart/AListApart#244]
Situation: I am a contributor who needs to change the email account associated with my account. I go to the profile edit page to do so.

Problem: Changing my email apparently requires inputting my password. I logged in via twitter so I don't seem to have a password.

Can we remove that restriction?

**Comment by murtaugh** [comment]
Do you happen to have the URL of the edit form you were on?

**Comment by murtaugh** [comment]
Belay that, it doesn't matter. The edit profile form checks for a password and prompts you to create one if it's missing, but I can see in the DB that you *do* have a password, so you've fallen into some sort of logic loop.

Have you tried the forgot password link? (http://alistapart.com/utilities/forgot-password)

This of course assumes you still have access to your old email address. If this isn't the case, I'd be happy to change it for you.

**Comment by jefflembeck** [comment]
Got in the old one, fixed it. Thanks @murtaugh
