### ISSUE TITLE
remove references to the d subdomain 

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#246]
A reader reported that images are broken on this article: http://alistapart.com/article/the-z-axis-designing-for-the-future. Talked with Tim; this seems to be an issue with the d subdomain. 
 
Reader report: https://twitter.com/gpakosz/status/614088145236312065

**Comment by murtaugh** [comment]
I have done a search and replace through the content fields in the database, swapping out `http://d.alistapart.com` for `/d/`.

@michellekondou can you take a quick peek and see if you can find any fields that I missed?

**Comment by michellekondou** [comment]
I checked all the fields
