### ISSUE TITLE
Broken links to the examples in CSS Positioning 101 article

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#248]
Reported by a reader.

Broken links to the examples in CSS Positioning 101 article: http://alistapart.com/article/css-positioning-101

There's a series of linked examples with the names example A, example B, example C, etc. And their corresponding links are 

http://alistapart.com/d/d/css-positioning-101/example_a.html
http://alistapart.com/d/d/css-positioning-101/example_b.html
http://alistapart.com/d/d/css-positioning-101/example_c.html, etc.

**Comment by michellekondou** [comment]
Hi, this was probably caused by a search and replace in the DB that was done yesterday, I'll check it out right away.

**Comment by michellekondou** [comment]
I see Tim has already replaced the error, when did the user report the issue?

**Comment by m1ca** [comment]
Reported on June 20, forwarded to Tim on June 21. I didn't hear back, so I thought maybe I should go ahead and create an issue here.

**Comment by murtaugh** [comment]
I tink we've fixed it in the meantime.
