### ISSUE TITLE
Some pattern library images are broken

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#250]
A reader says "many" pattern library images are broken and included a link to one of them.

http://patterns.alistapart.com/?url=/article-figure.html

**Comment by murtaugh** [comment]
Ah, the pattern library images are being called from the `d` subdomain that our host seems unable to keep stable.

**Comment by murtaugh** [comment]
@wilto @maban How do we rebuild the pattern library?

**Comment by maban** [comment]
Was this fixed? The images work for me.

**Comment by murtaugh** [comment]
The images work because sometimes the `d` subdomain works and sometimes it doesn’t. We need to rebuild the library without references to it.

**Comment by aparkening** [comment]
@murtaugh: is this fixed now that #246 is closed?

**Comment by murtaugh** [comment]
@maban @Wilto bumping: I still need some input on how to rebuild the pattern library so we can get rid of the links to the subdomain

**Comment by murtaugh** [comment]
All set. The pattern library's logic needed to be updated to be more flexible w/r/t hosting environments.

**Comment by aparkening** [comment]
@murtaugh: Is there anything that needs documentation for updating in the future, or did it turn out to be easy?
