### ISSUE TITLE
Event recap showing up in preview posts?

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#252]
There's some oddly formatted event recap info showing up in the footer of blog and column posts, but only when they're queued up prior to publication:

![screen shot 2015-07-05 at 2 29 07 pm](https://cloud.githubusercontent.com/assets/4195281/8536369/721c2410-241e-11e5-9dd5-0af518d9667c.png)

Once the post is live though, nothing is showing up: http://alistapart.com/blog/post/feedback-phases-and-personas

**Comment by rvwise** [comment]
Here as well
![2015-07-06_19-01-58](https://cloud.githubusercontent.com/assets/3172720/8536460/494ca034-2417-11e5-9afb-02fa3c0d09ea.png)

**Comment by marieconnelly** [comment]
Probably stating the obvious, but I think this is tied to when the categories get selected. I'm queueing up a post for later this week and initially didn't see this in the preview link, but when I remembered to go back to select the categories, it popped up again.

**Comment by michellekondou** [comment]
Corrected!
