### ISSUE TITLE
Update Picturefill and switch to native `picture` syntax

### ISSUE THREAD

**Issue by Wilto** [alistapart/AListApart#254]
I have a hunch that the `min-device-pixel-ratio` media query is causing the weirdness in #242—I’m not sure that syntax is long for this world, and _might’ve_ been dropped in some browsers already. We’re still using Picturefill 1.x and the pseudo-`picture` markup, so we can’t use the native `1x`/`2x` as-is. I’d recommend we switch over to Picturefill 2.3.1 and the real markup.

+@michellekondou @murtaugh

**Comment by murtaugh** [comment]
@Wilto Do you have any thoughts on strategy here? I guess I have two questions:

1. Do you think we should update all previous instances of the old markup?
2. How should we move forward? Is it as simple is adding the new, standards-based snippet to our style guide and installing the latest Picturefill?

**Comment by Wilto** [comment]
> Do you think we should update all previous instances of the old markup?

To do away with the MQ you mean, or switch over to the new markup?

> How should we move forward? Is it as simple is adding the new, standards-based snippet to our style guide and installing the latest Picturefill?

Yes indeed it is. 

```markup
<figure class="wide-hero" data-picture data-alt="">
	<div data-src="/d/_made/d/ALA_423_Container-Queries_480_220_81.jpg"></div>
	<div data-src="/d/_made/d/ALA_423_Container-Queries_960_440_81.jpg" data-media="(min-width: 600px)"></div>
	<div data-src="/d/_made/d/ALA_423_Container-Queries_1920_880_10.jpg" data-media="(min-width: 600px) and (min-device-pixel-ratio: 2.0)"></div>

	<!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
	<noscript><img src="/d/_made/d/ALA_423_Container-Queries_960_440_10.jpg" alt=""></noscript>

	<a class="issue-number" href="/issue/423"><span class="badge">Issue №</span> 423</a>
</figure>
```

Turns into:

```markup
<figure class="wide-hero">
	<picture>
		<source srcset="/d/_made/d/ALA_423_Container-Queries_1920_880_10.jpg" data-media="(min-width: 600px) and (min-device-pixel-ratio: 2.0)">
		<source srcset="/d/_made/d/ALA_423_Container-Queries_960_440_81.jpg" data-media="(min-width: 600px)">

		<img srcset="/d/_made/d/ALA_423_Container-Queries_480_220_81.jpg" alt="">
	</picture>
	<a class="issue-number" href="/issue/423"><span class="badge">Issue №</span> 423</a>
</figure>
```

**Comment by murtaugh** [comment]
> To do away with the MQ you mean, or switch over to the new markup?

I'm not sure what you mean by this — I meant, should we search-and-replace all the instances of the old pattern in our content?

**Comment by murtaugh** [comment]
The new picturefill is in place on dev: http://dev.alistapart.com/article/meta-moments-thoughtfulness-by-design

**Comment by murtaugh** [comment]
@erinlynch: I've updated the style guide with the new responsive image snippets: http://alistapart.com/about/ala-technical-style-guide#images

@mat, if you could just eyeball those and make sure they look ok it would be awesome.
