### ISSUE TITLE
Fix string to account for plural/singular on comment number 

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#257]
Currently the comments string says "1 Comments" instead of "1 Comment" 

![image](https://cloud.githubusercontent.com/assets/3171996/8666985/3e3b0a68-29f9-11e5-87c5-d18a3bdd81fe.png)

**Comment by murtaugh** [comment]
It doesn't say it anymore, which is strange. I don't think @michellekondou or I did anything.

**Comment by murtaugh** [comment]
Closing this for now, but will keep my eye open for it.
