### ISSUE TITLE
Right Sidebar Overlap w/ Speaker Deck Embed

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#258]
On http://alistapart.com/blog/post/on-our-radar-four-and-a-horse-stars, the sidebar components overlap oddly over the Speaker Deck embed at various screen sizes.

<img width="871" alt="screen shot 2015-07-17 at 12 36 42 pm" src="https://cloud.githubusercontent.com/assets/7241111/8752173/93e03e3c-2c80-11e5-8130-7f6cc61662a9.png">
<img width="725" alt="screen shot 2015-07-17 at 12 36 14 pm" src="https://cloud.githubusercontent.com/assets/7241111/8752174/93e661f4-2c80-11e5-953d-40aec2255e7d.png">

**Comment by beep** [comment]
Just chatted with @aparkening a bit about this. Some ratio-aware containers (#264) would definitely help here, but it seems like the article page’s current layout might be contributing as well? From what I can tell, the main content area is defined by [horizontal offsets on all of the child elements](http://cl.ly/image/0z3G1O18380j), which seems like it’d make it a little harder to establish ratio-aware containers.

If embedding third-party content is going to be fairly common, maybe it’s worth restructuring the article page?

**Comment by murtaugh** [comment]
Turns out I was over-thinking this, and there was a very simple solution: applying `overflow: hidden` to `figure` elements.

It seems to be working in the examples I've tested, whether they're videos, or regular images, or the above Speaker Deck embed.

**Comment by aparkening** [comment]
@murtaugh: I'm still seeing the incorrect behavior (and no overflow: hidden) on http://dev.alistapart.com/blog/post/on-our-radar-four-and-a-horse-stars, and I've cleared my cache.  Is this awaiting deployment to the dev server?

**Comment by murtaugh** [comment]
The fix is on a different branch that the on being published on dev right now.
