### ISSUE TITLE
update instances of the old picturefill in articles

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#263]

**Comment by aparkening** [comment]
Hey @erinlynch, can you give me an update of where you're at with updating picturefill?  I'm thinking about how many articles you have left, how much time you think it'll take, etc.  Thanks!

**Comment by erinlynch** [comment]
It’s underway. I had a long week last week and was not able to get it done. I will push to finish up this week.

**Comment by aparkening** [comment]
@erinlynch: Did you happen to update these, or are there still some articles that are in-process?

**Comment by aparkening** [comment]
Hey @erinlynch: Any update here?
