### ISSUE TITLE
Create Aspect Ratio-Aware Containers for Embeds

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#264]
As seen in #258, we need a way for content creators to embed media (like in http://alistapart.com/article/creating-intrinsic-ratios-for-video) so that the media doesn't run into the sidebar in various screen sizes.

**Comment by murtaugh** [comment]
Aaron — this happens even if the media is in an aspect ratio-aware container. The problem is that even with that technique, the floated elements cause the overlap.

**Comment by aparkening** [comment]
Not the right solution, so closing.  Problem solving is in #258.
