### ISSUE TITLE
CSS Positioning Article links to a malware/virus scam page

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#265]
Reported by a reader.
http://alistapart.com/article/css-positioning-101

The link is titled "some techniques" under the "Inherit-Something for Nothing: In Action" section.

The website takes over your browser, and won't let you close the tab, and keeps repeating with more urgent popups that you have a virus and need to call a 1800 number to fix it.

**Comment by m1ca** [comment]
![image](https://cloud.githubusercontent.com/assets/1951617/8780284/0528a884-2ed6-11e5-932f-29fbd9bb7aa8.png)

**Comment by murtaugh** [comment]
I removed the link, thanks.
