### ISSUE TITLE
Design: Header & Footer cropped

### ISSUE THREAD

**Issue by MikaCaldera** [alistapart/AListApart#268]
###### Issue viewed on following setups:  
*Mac OS - Chrome*
*Windows 10 - Chrome*

###### Example pictured below. 

![alistapart](https://cloud.githubusercontent.com/assets/5650312/9066897/2b2731f8-3aa8-11e5-9c9e-b37856ea38ea.PNG)

**Comment by murtaugh** [comment]
Hi Jessika! Those are actually design choices, albeit design choices that many smart people have misinterpreted as bugs, so perhaps we were a bit too ambitious in our out of the box thinking.
