### ISSUE TITLE
Figures missing in Colin's article

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#270]
As reported on Twitter: https://twitter.com/deanfroslie/status/629018505858392064

Colin's article: http://alistapart.com/article/approaching-content-strategy-for-personalized-websites

For example: 

![screen shot 2015-08-05 at 6 25 19 pm](https://cloud.githubusercontent.com/assets/4195281/9099524/60b24194-3b9f-11e5-9403-073736f8b493.png)

**Comment by murtaugh** [comment]
Oops, we accidentally removed the call to the old picturefill script, which we need until the new pattern is everywhere.
