### ISSUE TITLE
Taxonomy: Add new categories to blog posts

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#276]
1. Tim: send Marie csv of all blog posts, so she can begin adding categories via spreadsheet.
2. Marie: mark each blog post on csv with new categories available at https://docs.google.com/spreadsheets/d/1QGla_Yw0q92fubPiL9m9j1G8kTq7t01LWWCcw59G7uk/edit?usp=sharing.

**Comment by marieconnelly** [comment]
I should be able to get started on this next week! When the time comes, if it's possible to get a CSV with title & link for each post, that would be hugely helpful when I start adding categories. 

Also, @aparkening, have we made any decisions on how to categorize things like link posts and OOR/10 Years Ago in ALA, etc.? That may be a question for Sara, but I don't remember if those kinds of things really fit in the new taxonomy. 

Not sure if this is a question for @aparkening or @murtaugh, but definitely let me know the best way to include multiple categories (separate columns?) and how to indicate which is the primary category (i'm guessing the first one listed would be primary?) Thanks!

**Comment by murtaugh** [comment]
Here's the report: http://alistapart.com/reports/all-blog-posts

If you want to add columns for categories, that's cool. Someone will be entering these through EE, there's no way to automate assigning these.

**Comment by sarawb** [comment]
@marieconnelly I think link posts maybe don't need a category (and we aren't really writing new ones of those anyway), but OOR can probably go to Web Industry?

**Comment by marieconnelly** [comment]
Awesome - thanks, @sarawb!

**Comment by aparkening** [comment]
Priorities have shifted away from taxonomy work.  Closing to revisit another day.
