### ISSUE TITLE
Deck ads not showing up on individual article/column/blog posts

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#277]
Currently not seeing Deck ads on blog posts, columns, or articles—but am seeing them on the blog homepage, article list, etc. Not sure if this is related to #255? 

Susan's latest blog post: http://alistapart.com/blog/post/building-to-learn/
![screen shot 2015-08-14 at 9 24 26 am](https://cloud.githubusercontent.com/assets/4195281/9274755/498faab0-4266-11e5-857a-8165a2ebe433.png)

Blog homepage: http://alistapart.com/blog

![screen shot 2015-08-14 at 9 25 06 am](https://cloud.githubusercontent.com/assets/4195281/9274771/615d233e-4266-11e5-8884-089343cf2f1d.png)

**Comment by michellekondou** [comment]
Fixed! It was a temporary script misplacement between branch switching.
