### ISSUE TITLE
related content: upcoming event has the wrong description

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#278]
This is an upcoming event, so it should be a "recap":

![screen shot 2015-08-14 at 12 23 17 pm](https://cloud.githubusercontent.com/assets/308752/9278526/60f3fddc-427f-11e5-9cbe-c2200e837a4a.png)

**Comment by michellekondou** [comment]
It's the stricter EE conitionals again - it needed brackets around the date variables
