### ISSUE TITLE
add `entry-summary` to description meta tag

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#283]
to see if Readability grabs it.

**Comment by shanti-imagine** [comment]
Some articles that aren't playing nice with Readability:
http://alistapart.com/article/reclaiming-social-content-strategy-for-social-media
http://alistapart.com/article/thinking-responsively-a-framework-for-future-learning
http://alistapart.com/article/universal-design-irl
http://alistapart.com/article/using-responsive-images-now

I'm sure there's more but I haven't gone through every single one.

**Comment by murtaugh** [comment]
That's such a huge failure, for it not to even pick up the title, it can't be a problem on our side. I'll send Readability an email, see if they know what's up.

**Comment by shanti-imagine** [comment]
Indeed. Hmm, I was just about to give you some examples of your other articles that I managed to save just fine on my Readability (or at least used to). After looking through, now none of them appear on my desktop Readability anymore. What a bummer.

**Comment by murtaugh** [comment]
It's ironic, since the example URL they give is from ALA.

![screen shot 2015-10-07 at 12 09 50 pm](https://cloud.githubusercontent.com/assets/308752/10343587/5f0e895a-6cec-11e5-87ca-36f441f96c7f.png)

**Comment by shanti-imagine** [comment]
quite.
