### ISSUE TITLE
Date Error on Latest Article Post

### ISSUE THREAD

**Issue by nickbasile** [alistapart/AListApart#287]
![screen shot 2015-09-15 at 7 06 28 am](https://cloud.githubusercontent.com/assets/10423440/9876025/86ce2084-5b78-11e5-88ab-4ac3ed8cf493.png)

On the Designing Safer Web Animation For Motion Sensitivity article located on the Article page, the date is displaying incorrectly and unformatted.

**Comment by aparkening** [comment]
Thanks for the heads up @nickbasile, we'll take a look.

**Comment by aparkening** [comment]
@murtaugh: I'm also seeing an issue number error on http://alistapart.com/author/valhead.

**Comment by murtaugh** [comment]
I suspect EE's native Relationship field is a bit buggy... (cc: @michellekondou)

**Comment by michellekondou** [comment]
Both issues fixed; thanks for catching those @nickbasile and @aparkening!
