### ISSUE TITLE
Unpublished posts appearing as live links in the sidebar

### ISSUE THREAD

**Issue by redsesame** [alistapart/AListApart#288]
It looks as though unpublished posts appear as live content in the "related content" sidebar. 

![screen shot 2015-09-16 at 4 03 54 pm](https://cloud.githubusercontent.com/assets/9749204/9916943/fdc1028c-5c8c-11e5-893f-b9e9d514deda.png)

They don't appear in the "More from ALA" content in the footer, but the live URLs are being used in the "Recently by" sidebar.

**Comment by murtaugh** [comment]
I think I've taken care of this on the live site. Now I will update the repo.

**Comment by murtaugh** [comment]
This is "waiting for deployment" but has already been fixed on prod.

**Comment by aparkening** [comment]
Thanks @murtaugh!
