### ISSUE TITLE
Can't delete comments

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#289]
There's a duplicate comment on [Susan's recent post](http://alistapart.com/blog/post/stop-cringing-and-embrace-the-unknown#comments) but when I try to remove the post, it just bumps me back up to the top of the page:

![aladeletecomments](https://cloud.githubusercontent.com/assets/4195281/9959647/9f8cd800-5de3-11e5-920e-0bf7850734b4.gif)

**Comment by michellekondou** [comment]
@marieconnelly the funcitonality is restored, I deleted the comment. @murtaugh I restored the template to a previous condiiton to get it working.

**Comment by michellekondou** [comment]
Its ok now new functionality and ability to edit / delete comment - a class was missing

**Comment by aparkening** [comment]
Thanks @michellekondou!
