### ISSUE TITLE
Formatting in blockquotes

### ISSUE THREAD

**Issue by redsesame** [alistapart/AListApart#290]
When marking text as a blockquote, we need to be able to include list formatting.

Here is an example from http://alistapart.com/article/privacy-is-ux/:

![screen shot 2015-09-21 at 11 30 45 am](https://cloud.githubusercontent.com/assets/9749204/9997340/9d626e3c-6059-11e5-9fb3-38175c2d3330.png)

The text is quoting a bulleted list. It's marked up as an unordered list, but the bullets don't render, making it incorrect and difficult to read.

In general we should be able to apply any standard formatting (bold, italic, linking, lists) to any quoted text. Thank you!

**Comment by aparkening** [comment]
Any other formatting you want within blockquotes, other than bold, italic, linking, and lists, @redsesame?  "Standard formatting" can vary, so I'd be sad if we missed a formatting option that would be amazing for you.

**Comment by redsesame** [comment]
I can't think of anything other than those! Can you also check with Caren?
Thank you!

**Comment by litherland** [comment]
Can’t think of anything beyond that. I’m curious about how best to represent emphasis (`<em>`) within block quotes, but that’s probably more of a house style question for me and LMM.

**Comment by michellekondou** [comment]
I've added styles for 
* lists
* bold
* em
To represent <em> I've inverted the style, i.e. <em> in a <blockquote> has font-style: normal (not italic), as per Tim's suggestion.
(links were already working)

**Comment by aparkening** [comment]
@redsesame and @litherland: do lists, bold, and em work for you?

Let me know if this is sorted, and we'll close the issue out.

**Comment by litherland** [comment]
Thanks for this. I’m assuming that `strong` and `cite` are also accounted for; if so, I think we can close this out.
