### ISSUE TITLE
Formatting in tables

### ISSUE THREAD

**Issue by redsesame** [alistapart/AListApart#291]
We need to be able to format text within tables (bold, italics, linking, lists), as well as change borders and cell colors. In other words, table styling needs to be way more flexible.

Here is a good example of where table formatting isn't working well, via http://alistapart.com/article/privacy-is-ux/:

![screen shot 2015-09-21 at 11 32 39 am](https://cloud.githubusercontent.com/assets/9749204/9997468/4cd2cd3a-605a-11e5-8fb8-5a92e927605e.png)

Here, we need the first and third columns to use bold text to separate them from the second and fourth columns, and some kind of dividing line between the second and third columns. The background colors of the rows are also unnecessary and distracting, since they overemphasize the rows all the way across; here, it'd be better to have a background color on the header row and no colors in the tables themselves.

The specifics are less important here than the overall flexibility of formatting. We need to be able to change colors and styles according to the table content. Thanks!

**Comment by litherland** [comment]
I second LMM’s recommendations.

**Comment by aparkening** [comment]
@litherland and @redsesame: could we get 2 more examples of the kind of table flexibility that would be helpful for you?  This is complicated enough that we'd like to add these to a style guide, and we'd like the demo cases to be as useful as possible for you.

**Comment by aparkening** [comment]
@litherland and @redsesame: Any other examples of table formatting that would be helpful?  As mentioned, we'd like to create demonstration cases that are as useful as possible for you.

**Comment by redsesame** [comment]
This is all I can think of off the top of my head; Caren, can you think of
anything else? Sorry if this isn't specific enough!

   - being able to control which cells are shaded (sometimes we need the
   header row and nothing shaded in the table, other times certain cells,
   other times every other column, etc.)
   - being able to make text bold and italic
   - being able to have carriage returns in a single cell

**Comment by litherland** [comment]
Can’t think of anything else, LMM.

**Comment by michellekondou** [comment]
@redsesame @litherland @aparkening @murtaugh 
I've added lots of table examples in http://alistapart.com/about/ala-technical-style-guide#tables. I also included tips for best practices, and detailed guides on how to use borders, backgrounds, inline styles, carriage returns.
Let me know if the examples and language are clear, feel free to suggest corrections (for both structure and syntax)!
Thank you all :)

**Comment by redsesame** [comment]
Holy wow. That is elaborate and thorough and amazing. THANK YOU MICHELLE.
At first glance it looks positively excellent, but when we actually go to
use these tables I may have to ping you with questions to make sure I
understand the details. THANK YOU SO MUCH.

**Comment by awkawk** [comment]
Looks great, a few comments.

1) related to the comment about <caption>, I'd say:
If brief descriptive text is used to describe the table, for accessibility purposes that text should be contained within a <caption> element.  The caption element must be the first thing...

2) Do we want the figure element code in the "grab the HTML" sections?  If we are trying to give people the table html then I'd think not?

3) Tables 5 and up stop using scope - we should use it consistently for tables that can make use of it. The TH's in 5-8 need scope="col" (except for the row TH cells in table 5 which get scope=row.)

4) Table 6's TH elements are closed with TD closing tags. Same with Tables 7 and 8.  I can't tell you how many times I've done this...

5)

**Comment by michellekondou** [comment]
@redsesame feel free to ping me anytime!
@awkawk Thank you so much for the valuable feedback and for catching the mistakes!
I'm actually looking for solutions to implement responsive tables, so I'm going to slightly change the markup in the gists, and ask you to check again, if you don't mind.

**Comment by litherland** [comment]
Fantastic. Thanks so much, Michelle.

**Comment by michellekondou** [comment]
I'm closing this, we can continue this discussion in issue #308 https://github.com/alistapart/AListApart/issues/308
