### ISSUE TITLE
Difficulty of migrating all author data to the Authors channel?

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#292]
(I feel like this might be a duplicate discussion, but I didn't see it...)

@michellekondou: Can we assess the difficulty of migrating all author data from the Members module over to the Authors channel? (We should probably re-name it "People".)

Off the top of my head:

1. Define a full set of people-related fields (the set we have now was defined with the event templates as the main user of the data).
0. Update any authorship-related template logic to check for channel data first, falling back to member data.
1. Create a json/xml file out of the author data
2. Use [DataGrab](https://devot-ee.com/add-ons/datagrab) to import the data
3. Manually check each entry for correctness (assigning the right author to the new entries might be fragile), plus there will be new fields the import won't cover (I'm thinking a "Role" field, eg, Author, Illustrator, etc.) (This leaves open the possibility of a more robust Member profile capability for commenters in the future.)
4. Re-assign authorship of all entries to a new Relationship field instead of the User field (which we will hopefully be able to ditch).

That last item is the worst, but is not urgent and may not be strictly required, as we could continue to use the existing User field data until that last item is complete.

What else am I not thinking of?

Benefits:

1. Not having to edit author data via the members module
2. Not requiring a new member for every author — just store their info like any other piece of content. If a new author wants to edit it, they can create an account and we can assign them authorship of their channel entry.
3. Template-building will be more

cc @sarawb

**Comment by michellekondou** [comment]
So we only create a member if the Author wishes to sign in, right?

**Comment by aparkening** [comment]
Authors channel now exists on production. @michellekondou is refining the workflow.
