### ISSUE TITLE
Website Form Changes

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#294]
@litherland will be inputting wording and functionality changes to the forms by October 5, as discussed in Slack on September 24.

**Comment by litherland** [comment]
@aparkening, I’ve set up individual gdocs for the forms we discussed:

1. Create new comment account: https://docs.google.com/document/d/1Ish5nUP1H3YAqO7Q8zNbxRtYPc489u0tKgElDkY6Elg/edit?usp=sharing

2.  Reset password: https://docs.google.com/document/d/1Bcw5_WKxGDtr8jvpflobzPILU5-WZfihXfMTmcbmnoc/edit?usp=sharing

3. Sign in: https://docs.google.com/document/d/1pgGq3IaljsyaJ7MWNRfl5ApsI2MGENh2JNz8OuEM38U/edit?usp=sharing

4. Create comment: https://docs.google.com/document/d/1Ju3O8Qc3ldtuQkmyOMLHoRAska0Gbl5uMOSNESHvRGg/edit?usp=sharing

5. Edit profile: https://docs.google.com/document/d/1lzVIfInvmfYEmg2z0tAfsYfb2DcNYSp-p0x01BmXOQU/edit?usp=sharing

**Comment by aparkening** [comment]
The URLs we're talking about here are:
1. Create new comment account (http://dev.alistapart.com/tools/register)
2. Reset password (http://dev.alistapart.com/tools/forgot-password)
3. Sign in (on any dev.alistapart.com post with comments turned on)
4. Create comment
5. Profile page (http://dev.alistapart.com/edit/profile)

**Comment by aparkening** [comment]
Note that we're no longer including Username as a field.  We're replacing both Username and Email with the Email.  On the Edit Profile page, that means we'll display the user's email address in a way that shows they can't change it easily (probably as text, rather than a greyed form field).

**Comment by aparkening** [comment]
As per Slack: on /tools/register we've decided to keep all 3 fields required, and we'll make "(required)" grey.

**Comment by aparkening** [comment]
In Safari, help text is losing spaces.  Both http://dev.alistapart.com/tools/register and the login form.

Screenshots:
- Register: https://alistapart.slack.com/archives/tech/p1445264200000047
- Login: https://alistapart.slack.com/archives/tech/p1445264287000054

**Comment by aparkening** [comment]
Looks like word-spacing: -100% is the cause.

**Comment by aparkening** [comment]
Stick with "log in with" instead of sign in with: https://alistapart.slack.com/archives/tech/p1445265714000124

**Comment by litherland** [comment]
Also, related to the third item in Aaron’s list: I’ve simplified the help language on the password field to “Forgot?” Let’s make sure this is consistent. Screenshot is from http://dev.alistapart.com/article/thinking-responsively-a-framework-for-future-learning#comments
<img width="622" alt="screen shot 2015-10-19 at 10 50 24 am" src="https://cloud.githubusercontent.com/assets/618537/10581246/b7271974-764f-11e5-8ab5-e6d60155d9b7.png">

**Comment by aparkening** [comment]
Update "Password (Forgot it?)" to be "Password (Forgot?)" on in-page sign-in form: http://dev.alistapart.com/blog/post/on-our-radar-four-and-a-horse-stars/comment-sign-in

**Comment by aparkening** [comment]
"Discuss this article. We reserve the right to delete flames, trolls, and wood nymphs.
(The commenting engine will accept simple HTML tags.)" looks like different wording than what's in the Google Doc? http://dev.alistapart.com/blog/post/on-our-radar-four-and-a-horse-stars

Doc: https://docs.google.com/document/d/1Ju3O8Qc3ldtuQkmyOMLHoRAska0Gbl5uMOSNESHvRGg/edit

**Comment by litherland** [comment]
The wood nymph language appears only when the user is logged in. That
should remain as-is (stet).

**Comment by aparkening** [comment]
Righto, thanks @litherland.

**Comment by aparkening** [comment]
@michellekondou: Is the following Google profile wording still needed on /edit/profile?  I thought we were doing this differently now?

"Add the whole URL for your profile. For example:
http://google.com/+TimMurtaugh
or
https://plus.google.com/104877852135164107223‎"

**Comment by aparkening** [comment]
When I submit the /edit/profile form with an avatar file other than jpg, etc., I get taken to a whole new page that says:

"Oops—the form you submitted contained the following errors.
Images must be one of the following image types: jpg, jpeg, gif, png
Return to the previous page ∙ Log In"

Questions:
1. We do inline validation for all the other fields; can we do that for the avatar, too?
2. If we need to keep this second page, does it make sense to keep "Log In," since the person is already logged in to submit the form?
3. If we need to keep this second page, @litherland: any changes you want to make to the wording?

**Comment by aparkening** [comment]
Please change the "New password" title to "New password (if you want one)," as per https://alistapart.slack.com/archives/tech/p1445269637000173 and updated Google Doc (https://docs.google.com/document/d/1lzVIfInvmfYEmg2z0tAfsYfb2DcNYSp-p0x01BmXOQU/edit)

**Comment by litherland** [comment]
Updated the gdoc for consistent error message language.

Request: can we cap JPG, JPEG, PNG, GIF (to conform to ALA style)? Also, any way to insert a full stop after that list to complete the sentence?

<img width="604" alt="screen shot 2015-10-19 at 12 14 07 pm" src="https://cloud.githubusercontent.com/assets/618537/10583500/509d220a-765b-11e5-8701-e7fc0e680bec.png">

**Comment by aparkening** [comment]
As per Slack chat, editors can change the wording of system message copy in the control panel: Tools -> Utilities -> Translation Utility -> core_lang.php

**Comment by aparkening** [comment]
@litherland and @michellekondou: anything left to do on this issue?  I believe Caren will be creating new issues for the individual system message wording she wants to change.

**Comment by litherland** [comment]
One more thing occurs to me as I look at the image posted: let’s remember to cap JPG, JPEG, PNG, GIF (to conform to ALA style). Also, can we insert a full stop after the error list to complete the sentence?

**Comment by michellekondou** [comment]
@aparkening  
Done! 
This phrase was in Tools -> Utilities -> Translation Utility -> member_lang.php.
@litherland Caren you may want to have a look at those phrases too!

**Comment by litherland** [comment]
@michelle, I absolutely would like to look at those. Thanks!
