### ISSUE TITLE
Image/text overlay issue on related content items 

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#295]
Illo and content aren't playing nicely together: 

![image](https://cloud.githubusercontent.com/assets/3171996/10107728/0c1e31e2-638b-11e5-9f89-9c213d7a9dbc.png)

http://alistapart.com/article/web-animation-at-work 

I'm on Chrome 45.0.2454.99.

**Comment by murtaugh** [comment]
`max-height: 100%` is apparently not sufficient for Chrome.
