### ISSUE TITLE
Event that's not published yet (in progress in EE) showing as related content on live site

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#296]
Event entry is still "in progress" in EE but the content is already pulling into related content sidebars. 

![image](https://cloud.githubusercontent.com/assets/3171996/10107867/d096afea-638b-11e5-8649-f8f7d766ca1f.png)

Screenshot from: http://alistapart.com/blog/post/design-tools-what-are-you-using.

**Comment by sarawb** [comment]
Seemingly same/similar to https://github.com/alistapart/AListApart/issues/288 from a couple weeks ago.

**Comment by murtaugh** [comment]
It is, which is why I'm surprised to see it. Must have missed something.

**Comment by murtaugh** [comment]
Yep, found the thing I missed.
