### ISSUE TITLE
Article URL is changing itself

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#302]
http://alistapart.com/article/css-positioning-101 

is redirecting to 

http://alistapart.com/article/css-positioning-10 

(and the 404 page).

**Comment by m1ca** [comment]
This is also happening to:
http://alistapart.com/article/css-floats-101/

which redirects to

http://alistapart.com/article/css-floats-10

**Comment by m1ca** [comment]
A 3rd email came in! Apparently the links were functioning yesterday.

**Comment by murtaugh** [comment]
@michellekondou, I assume this has something to do with your htaccess work. I took a look at recent commits, but didn't find what the culprit is.

**Comment by michellekondou** [comment]
Ok found it and corrected it, it was a typo
