### ISSUE TITLE
Broken links on author's bio pages

### ISSUE THREAD

**Issue by motionsuggests** [alistapart/AListApart#304]
On the author's bio pages the link to the author's site is broken. I've tested it on Chrome, Firefox and Safari all on OSX 10.9.5.

Checkout http://alistapart.com/author/bradfrost. The href on the link to Brad's site is http://http//bradfrostweb.com/. See attached for more info. 

![alistapart_author_link_broken_1](https://cloud.githubusercontent.com/assets/181652/10792330/a245683e-7d62-11e5-9aea-c28e185af58f.jpg)
![alistapart_author_link_broken_2](https://cloud.githubusercontent.com/assets/181652/10792329/a24527c0-7d62-11e5-9d2a-b2ba5dff23cf.jpg)

**Comment by murtaugh** [comment]
Thanks! I'l fix this up now.

**Comment by murtaugh** [comment]
@michellekondou It looks like the Parse URL plugin has stopped working altogether.
