### ISSUE TITLE
Improve Responsive handling of complex tables

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#308]
More complex tables don't look amazing in every device.  Let's improve it!

**Comment by michellekondou** [comment]
@aparkening @litherland @awkawk @redsesame 
I made many new corrections to http://alistapart.com/about/ala-technical-style-guide#tables, I hope I've got everything covered!

For table display in different resolutions (responsive tables) we decided to use a no JS solution by Aaron Gustafson. For it to work correctly, when creating a table we need to fill in the values for the data-title attribute on the td element, its really simple, there are many copy paste examples (gists) in the technical style guide (http://alistapart.com/about/ala-technical-style-guide). 
Let me know if it's all clear,
Thank you!

**Comment by michellekondou** [comment]
I replaced all instances of tables in the DB, to have a class of not-rwd. To avoid having to manually replace all instances of past tables with the markup needed to correctly display the responsive layout, we decided it would be ok for the old tables to have a horizontal scroll if the content does fit in the screen.
