### ISSUE TITLE
Suggestion: Adding Editor Notes for RSS Feed

### ISSUE THREAD

**Issue by JasonNeel** [alistapart/AListApart#313]
I noticed this quirk several months ago with the release of Issue 423 and, more specifically, the article “[Create a Content Compass](http://alistapart.com/article/create-a-content-compass)” by Megan Casey. It has since resurfaced with “[How We Hold Our Devices](http://alistapart.com/article/how-we-hold-our-gadgets)” in Issue 432. Note that both of these articles are (wonderful) book excerpts.

I get notified about new content on ALA via the RSS feed. I began reading Megan's article in my RSS reader, but became slightly confused when the text lead off with “Chapter 2 mentioned…” It didn’t take me long to understand that what I was reading was, in fact, an excerpt from a book, but there was no indication of this fact in the RSS entry. In fact, I would not have been as confused by this had I just opened the actual webpage for the article instead of reading from the RSS feed, as there is a notice on the article page explaining this fact.

My suggestion is to integrate the ExpressionEngine field `{article_editors_note}` and the related conditional logic found on [line 158 of the article template](https://github.com/alistapart/AListApart/blob/master/templates/default_site/article.group/index.html#L158) into the [RSS feed template](https://github.com/alistapart/AListApart/blob/e70e5c44d678f870de6b6a80dfd9fb2ceceac61d/templates/default_site/main.group/feed.feed#L29). This would end up being very much like the way article footnotes are included in the feed. While this is a very minor detail, I think it can help clear up a little bit of confusion for RSS users like me.

**Comment by aparkening** [comment]
Thanks for letting us know about the lack of editor notes in the RSS feed, @JasonNeel.  We completely agree editor notes would be helpful here, and we'll give an update once they're sorted.

**Comment by murtaugh** [comment]
All set, I hope. I've added editor's notes for articles, columns, and blog posts in all our feeds.

**Comment by JasonNeel** [comment]
Thanks, guys!
