### ISSUE TITLE
RSS tag list (dc:subject) contains HTML

### ISSUE THREAD

**Issue by abackstrom** [alistapart/AListApart#315]
The `<dc:subject>` portion of the RSS feed currently contains HTML. This breaks in NewsBlur, my RSS reader of choice. I'm not intimately familiar with RSS or the Dublin Core but I don't believe the field should contain HTML.

    <dc:subject><![CDATA[<a href="/topic/css"><span itemprop="about">CSS</span></a>,
    <a href="/topic/web-strategy"><span itemprop="about">Web Strategy</span></a>]]></dc:subject>

**Comment by nelsonjchen** [comment]
For reference, it blows up like the pictures mentioned in this problem report on Newsblur. As a user of Newsblur, I have never seen another feed do anything like this.

https://getsatisfaction.com/newsblur/topics/the_tags_for_the_posts_from_a_list_apart_are_not_parsed_correctly

**Comment by aparkening** [comment]
Thanks for letting us know (and providing some helpful screenshots), @abackstrom and @nelsonjchen.  We'll investigate!

**Comment by nelsonjchen** [comment]
Thanks! I have some another link here. It's two years old though but I guess @samuelclay 's email back then went into a black hole.

https://getsatisfaction.com/newsblur/topics/the_tags_for_the_posts_from_a_list_apart_are_not_parsed_correctly

**Comment by nelsonjchen** [comment]
Whoops, sorry about that last comment which I just deleted, accidently mashed comment when closing the tab. 

Thanks for looking into this!

**Comment by samuelclay** [comment]
Hey, I run NewsBlur and would be happy to help in any way.

**Comment by aparkening** [comment]
Hey @samuelclay, Michelle will be following up on this thread shortly, as she removed the HTML from the RSS feed.

You mentioned that you emailed us and didn't receive a response.  Would you mind letting me know which email address you used?  I don't see an email from you in our usual inboxes, so I'd like to investigate further.

**Comment by samuelclay** [comment]
I couldn't find the email, which means I probably never sent it. I send quite a few of these types of emails to publishers, so I assumed I did the same here. That's too bad, too, since it looks like you folks are on top of issues. Wish I would've emailed sooner! Thanks for your help, too.

**Comment by michellekondou** [comment]
Hi @samuelclay! as @aparkening mentioned I've cleared the html from the <dc:subject>. I'm still not seing the change reflected in newsblur.com - the feed probably needs to be re-fetched or updated?

**Comment by nelsonjchen** [comment]
I believe you can force fetch feeds from the site settings.

![site settings](https://cloud.githubusercontent.com/assets/5363/11195567/61ebc120-8c67-11e5-8618-7460707ebf46.gif)

But I'm getting errors when I force it to refresh from A List Apart.

![error](https://cloud.githubusercontent.com/assets/5363/11195576/6e3a2e62-8c67-11e5-84e6-9ae2010ed13b.gif)

**Comment by michellekondou** [comment]
Thank you @nelsonjchen, I actually tried that and got the same error!

**Comment by samuelclay** [comment]
Looks good! NewsBlur doesn't update stories based on tag changes, so I just wiped out the existing stories and let NewsBlur take care of the rest. The stories came in just fine. Thanks!

**Comment by aparkening** [comment]
Thanks for reaching out @abackstrom, @nelsonjchen, and @samuelclay.  Please let us know if you spot any other issues in the future!
