### ISSUE TITLE
Login attempts display "The Web at 25..." page

### ISSUE THREAD

**Issue by Chapoton** [alistapart/AListApart#319]
All login attempts result in the following page being displayed. Page source is provided below as well.

![screen shot 2015-11-20 at 5 57 21 am](https://cloud.githubusercontent.com/assets/4986993/11301622/794a29a4-8f4d-11e5-901d-2cc5a394e026.png)

```

<!doctype html>

<!--[if lt IE 7 ]> <html class="ie ie6 ie-lt10 ie-lt9 ie-lt8 ie-lt7 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 ie-lt10 ie-lt9 ie-lt8 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 ie-lt10 ie-lt9 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 ie-lt10 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->

<head id="webat25.org">

	<meta charset="utf-8">
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>The Web at 25 (Coming Soon)</title>
	
	<meta name="google-site-verification" content="" />
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="stylesheet" href="/assets/css/reset.css" />
	<link rel="stylesheet" href="/assets/css/fonts.css" />
	<link rel="stylesheet" href="/assets/css/style.css" />

</head>

<body class="coming-soon">

<div class="wrapper" style="position: absolute; top: 50%; left: 50%; width: 50%; height: 50%; margin-left: -25%; margin-top: -25%; text-align: center; font-size: 1.4em;">

	<h1 style="margin-bottom: 2em;"><img src="assets/img/promo-logo.png" alt="The Web's 25th Anniversary"></h1>

	<p style="margin-bottom: 1em;">Brought to you by <a href="http://www.w3.org/People/Berners-Lee/">Tim Berners-Lee</a>, <a href="http://www.w3.org/">W3C</a> and the <a href="http://www.webfoundation.org/">World Wide Web Foundation</a>.</p>
		
	<p><strong>Coming soon.</strong></p>

</div>
  
</body>
</html>
```

##### Browser info (attempted on three machines)

* http://whatsmybrowser.org/b/GS6GZ8B
* http://www.whatsmybrowser.org/b/YBTPKBO
* http://www.whatsmybrowser.org/b/ILSPI7O

##### Troubleshooting attempts (without success):

1. Resetting password
2. Using different browser
3. Clearing browser cache
4. Using different machine

**Comment by murtaugh** [comment]
What page are you trying to login from?

**Comment by Chapoton** [comment]
Originally trying to leave a comment on the article [The $PATH to Enlightenment ](http://alistapart.com/article/the-path-to-enlightenment)

Then tried several other articles as well as the [ALA login page](http://alistapart.com/tools/log-in).

**Comment by murtaugh** [comment]
Ah, so it's interesting that this happened because now we know our offline template was accidentally written over at some point.

But, it's happening because you must have tripped our spam filter somehow, and your account was banned. I've just unbanned it.

**Comment by Chapoton** [comment]
Thanks! It now works. Appreciate the help.
