### ISSUE TITLE
Illustrator credit for non-illustrations

### ISSUE THREAD

**Issue by redsesame** [alistapart/AListApart#320]
For articles that have an image but not an illustrator, the image gets credited as Kevin Cornell. This comes up particularly for ABA excerpts. Example: http://alistapart.com/article/how-we-read

**Comment by sarawb** [comment]
The default as Kevin was a quick fix. It'd be good to fix and go back and tag all his as him, but a quicker answer might be to have an entry for A Book Apart, so those show up as courtesy of ABA? But then ABA would be an "author" in our cms. Hrmm. Tim would it make more sense to just add a checkbox like "no illustrator credit" we can tick?

--
Sara Wachter-Boettcher
(541) 517-2870
sarawb.com

**Comment by murtaugh** [comment]
I’m already doing that very thing Sara :D

**Comment by murtaugh** [comment]
New field in and tested on JSM's How We Read.

**Comment by aparkening** [comment]
Thanks Tim!
