### ISSUE TITLE
Dim "Previous" button when there is no previous content in News

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#325]
Submitted by a reader:

In the web page: http://aneventapart.com/news/videos/36 the "Previous" button should be disabled as clicking on it displays the "404 Not Found" error.

Translation: In the template, when there is no longer a "previous" item, the previous link/button should be disabled. This probably applies to all news genre templates, not just video, e.g. please check to see if this change is also needed on Basic posts, Speaker Spotlight posts, etc.

**Comment by murtaugh** [comment]
Hey Jeffrey — that seems to be a note for AEA, not ALA?

**Comment by zeldman** [comment]
Yep, my error, sorry.

**Comment by zeldman** [comment]
Can't seem to *delete*.
