### ISSUE TITLE
h2 (“Featuring”) on Events page suddenly has a weird character string

### ISSUE THREAD

**Issue by litherland** [alistapart/AListApart#329]
This morning, Rose noticed that “Featuring” inexplicably has a weird character string after it (“asd”). That should probably be cleaned up as soon as possible. Template issue?

<img width="722" alt="screen shot 2015-12-01 at 9 45 17 am" src="https://cloud.githubusercontent.com/assets/618537/11504372/f8f23f98-9812-11e5-90b9-e01ba468ecbc.png">

**Comment by michellekondou** [comment]
On it!

**Comment by michellekondou** [comment]
Done
