### ISSUE TITLE
Reduce Website Navigation Items

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#335]
I haven't seen any official wording changes, and I believe we can remove Columns, Blog, and Events, so that we only show the logo, Articles, Topics, and Write For Us.

Articles will go to the new content river referenced in #334.

**Comment by murtaugh** [comment]
As per Mica, we are not removing events.

**Comment by aparkening** [comment]
Layout on Dev looks great.  This can be deployed with the other changes.
