### ISSUE TITLE
Issue Bug Bug in Specific Article

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#337]
“Resetting Agency Culture” in Issue No. 421 displays as Issue No. 0. (Screenshot attached.) http://alistapart.com/article/resetting-agency-culture

And if you click the “0” Issue bug, it takes you to the /articles/ page instead of to the issue page. Weird.

No other articles I spot checked have this problem. All other old articles I checked display their correct issue №, and the Issue № bug on the other articles points correctly to the homepage of that issue.

We’re discontinuing issues anyway, and nobody has complained about this to my knowledge, but I found it curious and worth sharing. It may point to an underlying problem that does matter to us. (Or maybe it just means someone entered the wrong data into the CMS at some point.) 

A mystery to be sure.

![screen shot 2015-12-10 at 2 44 24 pm](https://cloud.githubusercontent.com/assets/2983799/11751400/486b133c-a007-11e5-8294-44b9daa74039.png)

**Comment by murtaugh** [comment]
Michelle found the issue with this yesterday, the fix will be deployed shortly.
