### ISSUE TITLE
Legacy article has <dd> and <dt> tags

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#341]
http://alistapart.com/article/typepad has no spacing between paragraphs due to tagging with `<dd>` and `<dt>`.

**Comment by rvwise** [comment]
I see the reason: it's supposed to present as an interview. I'll see how we're making those up up recently.

**Comment by rvwise** [comment]
The technical style guide has [the right markup](http://alistapart.com/about/ala-technical-style-guide#interview-qa-format).

**Comment by aparkening** [comment]
Thanks for following up and discovering the cause and solution, @rvwise!
