### ISSUE TITLE
Character encoding issue, “â€™” showing on page instead of “ ' ”

### ISSUE THREAD

**Issue by jhsware** [alistapart/AListApart#350]
An old article on the subject:

http://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC%E2%84%A2-showing-on-page-instead-of

![alistapart](https://cloud.githubusercontent.com/assets/3896884/12641024/80a290ec-c5ad-11e5-866d-0244dbb0ac5c.png)

**Comment by michellekondou** [comment]
@jhsware Just letting you know that was fixed on the spot, temporary DB issue. Thank you for letting us know though :)
