### ISSUE TITLE
`code` tags aren’t formatting as expected in `h1`s

### ISSUE THREAD

**Issue by litherland** [alistapart/AListApart#356]
Example: `<h1>Finessing <code>feColorMatrix</code></h1>` (http://alistapart.com/article/finessing-fecolormatrix)—“feColorMatrix” should be formatted as code.

(I’ve now removed the `code` tags from the title field because the formatting seems unpredictable.)

**Comment by murtaugh** [comment]
Removed the "critical" label, which should be reserved for "the word is ending" type issues.

**Comment by litherland** [comment]
Oy, sorry. (Thought we were hoping to resolve the issue before Una’s article went live at 10 a.m.)

**Comment by murtaugh** [comment]
@litherland Code in titles causes problems in a number paces, so in the past, we have used markdown notation. An example is here:

http://alistapart.com/blog/post/article-update-dont-rely-on-default-sizes

**Comment by litherland** [comment]
Okay. Thanks! (Had in fact considered doing that, but wasn’t sure how best to proceed.)
