### ISSUE TITLE
date formatting

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#357]
days of the month shouldn't have the leading zero:

![screen shot 2016-02-11 at 1 20 19 pm](https://cloud.githubusercontent.com/assets/308752/12985773/405e33d6-d0c2-11e5-88b6-a39a756c8a64.png)

**Comment by michellekondou** [comment]
It's in a few places, I've corrected it on the homepage, I'll go through the templates

**Comment by brettdewoody** [comment]
PR to remove the leading `0` in displayed dates - https://github.com/alistapart/AListApart/pull/412
