### ISSUE TITLE
missing author pages

### ISSUE THREAD

**Issue by meetar** [alistapart/AListApart#358]
http://alistapart.com/article/creating-intrinsic-ratios-for-video links to http://alistapart.com/author/tkoblentz which is a 404!

I just checked through L on http://alistapart.com/authors and found a few more author links which are 404s:
http://alistapart.com/author/mcaceres
http://alistapart.com/author/bhenick@twitter
http://alistapart.com/author/bhulin

:v:

**Comment by michellekondou** [comment]
Thanks for the heads up, we're onto it!
