### ISSUE TITLE
Found: links using /author/[articlename] instead of /article/[articlename]

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#359]
Reader reported incorrect urls for articles listed on a couple of author pages. They go to /author/[articlename] instead of /article/[articlename]

For http://alistapart.com/author/brianalvey 
Links to: http://alistapart.com/author/oz
Should link to: http://alistapart.com/article/oz

Jason Santa Maria's page: http://alistapart.com/author/jsm
Links to: http://alistapart.com/author/how-we-read
Should link to: http://alistapart.com/article/how-we-read

**Comment by michellekondou** [comment]
Corrected!
