### ISSUE TITLE
Content overflow field not displayed

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#361]
For http://alistapart.com/article/back-to-the-future-in-2016#work

The last entry of the main content field shows up (Ida Aalen under Work) but the overflow field (that starts with Geri Coady) is not being displayed on the site or in the CMS Live Look.

**Comment by zeldman** [comment]
FWIW, http://alistapart.com/article/back-to-the-future-in-2016#work also doesn't work. The link blinks out, almost as if it is going to time out, then redirects to plain old http://alistapart.com/article/back-to-the-future-in-2016 with no hash tagged ID. Entering http://alistapart.com/article/back-to-the-future-in-2016#work repeatedly does not lead to any link further down the page. What you were trying to highlight isn't viewable via link.

**Comment by michellekondou** [comment]
@m1ca @zeldman I've restored the overflow content field for the legacy articles (and cleared the cache for the specific article - I think it's the only one using this field).

**Comment by zeldman** [comment]
Thank you, @michellekondou !

**Comment by michellekondou** [comment]
@zeldman hashtag is working for me, i.e it's taking me to the link further down the page (the hashtag being removed form the url has to do with the way we've implemented the history api). I'll look into it further!

**Comment by m1ca** [comment]
Thank you, @michellekondou!

We had a lot of issues with the hashtags on this one back in January. Curious that they're being funky again. :/

**Comment by m1ca** [comment]
Oh, Michelle, the events pages use the overflow content fields for the transcripts.

**Comment by zeldman** [comment]
@michellekondou The hashtag began working again after you restored the overflow content field for the legacy articles and cleared the cache for this article. It did not work until you did those things. cc @m1ca

**Comment by michellekondou** [comment]
@m1ca events pages have different fields, they were not affected by this

**Comment by michellekondou** [comment]
@m1ca @zeldman  by the way I've installed the cloudflare module I've been working on to production, we now have the ability to purge individual urls through the Expressionengine control panel, and when an entry is updated the cache for that entry is automatically cleared, and more. I'll create a basecamp post with all the details.

**Comment by michellekondou** [comment]
Closing this!

**Comment by zeldman** [comment]
@michellekondou That sounds AMAZING and we've needed it so much. Thank you. (An Event Apart could probably use it, too, if you're willing to share.) Looking forward to your Basecamp post! cc @m1ca
