### ISSUE TITLE
Duplicated "more from this author" links when two authors are listed.

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#363]
Eric Meyer's "More from this author" links are duplicates of Sara Wachter-Boettcher's on their excerpt, and Sara's  "More from this author" links are duplicating mine. 

http://alistapart.com/article/design-for-real-life-excerpt#related
http://alistapart.com/article/design-for-real-life-interview-with-sara-wachter-boettcher#related

**Comment by michellekondou** [comment]
Corrected!
