### ISSUE TITLE
Load comment count so it is not cached by Cloudflare

### ISSUE THREAD

**Issue by litherland** [alistapart/AListApart#364]
See attached screenshot. A cursory look through other articles suggests that the issue is prevalent.

<img width="685" alt="screen shot 2016-03-30 at 11 52 32 am" src="https://cloud.githubusercontent.com/assets/618537/14149034/2e9ffcaa-f670-11e5-8f35-de13b2b1c211.png">

**Comment by murtaugh** [comment]
What’s also an issue is that all three of those seems to be spam.

**Comment by zeldman** [comment]
Thanks, Caren. Is anyone moderating comments these days? (I ask 'cause two
of those three comments are spam, and the third *might* be as well.)

…………………………………

Jeffrey Zeldman

A Space Apart

148 Madison Avenue, Suite 600

New York, NY 10016

917-746-4838


A Book Apart <http://abookapart.com> | A List Apart <http://alistapart.com/>
 | An Event Apart <http://aneventapart.com>

Big Web Show <http://5by5.tv/bigwebshow> | zeldman.com <http://Zeldman.com>
| @zeldman <https://twitter.com/zeldman>

**Comment by litherland** [comment]
I’ll get rid of ’em.

**Comment by litherland** [comment]
Ah, someone beat me to it! But I just went through and nuked some spammy
comments from a dozen or so older articles. (I think Marie may have been
handling that, but I’ll try to stay on top of it moving forward.)

**Comment by zeldman** [comment]
Thank you both!


…………………………………

Jeffrey Zeldman

A Space Apart

148 Madison Avenue, Suite 600

New York, NY 10016

917-746-4838


A Book Apart <http://abookapart.com> | A List Apart <http://alistapart.com/>
 | An Event Apart <http://aneventapart.com>

Big Web Show <http://5by5.tv/bigwebshow> | zeldman.com <http://Zeldman.com>
| @zeldman <https://twitter.com/zeldman>

**Comment by michellekondou** [comment]
I renamed the issue to what the real problem is, and getting to work on it!

**Comment by michellekondou** [comment]
Comment count is now loading with ajax - bypassing Cloudflare cache
