### ISSUE TITLE
RSS Feed Not Updating?

### ISSUE THREAD

**Issue by JasonNeel** [alistapart/AListApart#365]
Just wanted to drop you all a note: it doesn't seem as though your RSS feed has updated with the latest articles. The most recent content there is “Web Animation Past, Present, and Future” and not the two “Design for Real Life” pieces.

**Comment by michellekondou** [comment]
Thank you for the heads up! We recently tightened our cloudflare caching settings, but certain urls like the feed need to bypass cache.

**Comment by zeldman** [comment]
Thanks, Michelle. You are the bee's knees.

**Comment by JasonNeel** [comment]
Yay! They're there now. Thanks!
