### ISSUE TITLE
Load comment sign in and comment submit form differently to bypass caching

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#366]

**Comment by RitterKnightCreative** [comment]
Not sure of this is related but when I go to edit my own profile, I get a completely different user's profile.

**Comment by murtaugh** [comment]
Oops, looks like we have caching turned up too far. Thanks for the report!

**Comment by michellekondou** [comment]
@RitterKnightCreative thanks for catching this! Could you check if its working for you now?
