### ISSUE TITLE
Year needs updating in AEA banner

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#368]
Hi, someone pointed out that we need to update the AEA banner to say 2016. 

![image](https://cloud.githubusercontent.com/assets/1951617/14407914/2b14752e-feaa-11e5-89fc-f9bb5909d885.png)

**Comment by zeldman** [comment]
Good catch. The URL should be http://aneventapart.com  (no subpage)

Thanks, Mica, and thanks in advance, Michelle or Tim...



…………………………………

Jeffrey Zeldman

A Space Apart

148 Madison Avenue, Suite 600

New York, NY 10016

917-746-4838


A Book Apart <http://abookapart.com> | A List Apart <http://alistapart.com/>
 | An Event Apart <http://aneventapart.com>

Big Web Show <http://5by5.tv/bigwebshow> | zeldman.com <http://Zeldman.com>
| @zeldman <https://twitter.com/zeldman>

**Comment by michellekondou** [comment]
@m1ca @zeldman Done!
