### ISSUE TITLE
Reported ad issue on mobile

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#369]
An author looking at the site on android+latest Chrome says the Event Apart ad is broken on all pages he visited (and thinks the text was just too long)

**Comment by michellekondou** [comment]
This I can't reproduce, is anyone else seeing this?

**Comment by m1ca** [comment]
@michellekondou no, I have't been able to

**Comment by michellekondou** [comment]
@m1ca @murtaugh Since we haven't been to reporduce this I'm closing the issue!
