### ISSUE TITLE
should we be cropping photos?

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#372]
This photo is 4:3, i think

![screen shot 2016-04-12 at 1 25 27 pm](https://cloud.githubusercontent.com/assets/308752/14469312/11aa38c6-00b2-11e6-99ee-2f626c9eb530.png)

**Comment by michellekondou** [comment]
If the image is square (as the instructions say) it looks correct, so I don't know, should we change the instructions?

**Comment by murtaugh** [comment]
Maybe we should be cropping just in case? Maybe not. I admittedly didn’t read the instructions when I uploaded that photo to test the form :)

**Comment by michellekondou** [comment]
So I'm closing this then!
