### ISSUE TITLE
Related articles on "More from A List Apart" in the Issue page have broken url

### ISSUE THREAD

**Issue by FedericoBiccheddu** [alistapart/AListApart#376]

**Comment by murtaugh** [comment]
Hi Federico!

Can you give me an example of what you mean by the issue page?

**Comment by FedericoBiccheddu** [comment]
Hi @murtaugh,

for example: http://alistapart.com/issue/419

If you click on "**Meaningful CSS: Style Like You Mean It**", as you can see, the url is broken because there is the "/issue/" prefix. Is the same for the other articles.

**Comment by murtaugh** [comment]
Awesome, thanks for the report.

**Comment by murtaugh** [comment]
It will take a little time for the cache to clear, but I've pushed the fix, thanks again!
