### ISSUE TITLE
comments: user reports being shown an “edit” button even though he’s not the user in question

### ISSUE THREAD

**Issue by litherland** [alistapart/AListApart#377]
On Twitter, Stuart Robson mentioned being shown an edit button on someone else’s comment: https://twitter.com/sturobson/status/734812595341930503

This was re: Tim Baxter’s CSS article: http://alistapart.com/article/meaningful-css-style-like-you-mean-it

Decided to create an issue when I didn’t see any mention of this in Slack. Disregard if you’re already on it!

**Comment by zeldman** [comment]
Thanks, Caren!

**Comment by murtaugh** [comment]
Sigh, caching really throws a monkey in the wrench of useful features.
