### ISSUE TITLE
Article Page: Horizontal Scroll on Small Screen

### ISSUE THREAD

**Issue by michaelspellacy** [alistapart/AListApart#378]
Hi Alistaparters! 

I noticed a slight horizontal scroll when visiting the site via Facebook's iOS app. Was able to dupe it on Google Chrome (latest) on Mac OS (10.11)

Screen here: http://screencast.com/t/50vFxLbqwu0

It appears to be caused by an absolute width on .entry-header

` .entry-header { width: 960px; ...}`

Love the site!

**Comment by zeldman** [comment]
Thanks, Michael. Much appreciated. We will look into it after the holiday. Cheers! :)

**Comment by michellekondou** [comment]
@michaelspellacy @zeldman @murtaugh 
Thank you for catching that Michael - bug fixed!

**Comment by michaelspellacy** [comment]
Cool! Yes, conformed fix on this end! Glad I could help!
