### ISSUE TITLE
Time to remove "HAPPY COG" logo from alistapart.com footer

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#381]
Like the fella said, it is time to permanently remove the linked Happy Cog logo from the footer of every page of alistapart.com. Thank you!

**Comment by zeldman** [comment]
Brilliant. Can we add the A List Apart logo in its place?

…………………………………

studio.zeldman <http://studio.zeldman.com>
148 Madison Avenue, Suite 600
New York, NY 10016
917-746-4838

An Event Apart <http://aneventapart.com/subscribe> | A List Apart
<http://alistapart.com/> | A Book Apart <https://abookapart.com>
Big Web Show
<https://itunes.apple.com/us/podcast/the-big-web-show/id370445683?mt=2> |
zeldman.com | @zeldman <https://twitter.com/zeldman>

**Comment by michellekondou** [comment]
Added!

**Comment by zeldman** [comment]
Awesome. Thank you. Brands united!

…………………………………

studio.zeldman <http://studio.zeldman.com>
148 Madison Avenue, Suite 600
New York, NY 10016
917-746-4838

An Event Apart <http://aneventapart.com/subscribe> | A List Apart
<http://alistapart.com/> | A Book Apart <https://abookapart.com>
Big Web Show
<https://itunes.apple.com/us/podcast/the-big-web-show/id370445683?mt=2> |
zeldman.com | @zeldman <https://twitter.com/zeldman>
