### ISSUE TITLE
Captcha request each time someone visits the site

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#382]
One of our readers is presented with an "are you a human" captcha request on every visit. All works normally after the captcha, for the duration of each visit. 

He's located in Beijing, but has set things up so some CDN resources (i.e. Google fonts, anything Wordpress) are loaded through a proxy, because a lot of that stuff is blocked in China. Proxy server is in the US. 

He's using the latest Firefox.

**Comment by murtaugh** [comment]
That’s CloudFlare. He’s obviously, unfortunately, on a network that a lot of bad activity comes from, and CloudFlare is set to challenge users from areas where attacks are known to come from.

**Comment by m1ca** [comment]
And there's nothing anyone can do? He says it's making him visit the site less and less, he's so frustrated.
