### ISSUE TITLE
RSS feed URLs inconsistent or erroneous

### ISSUE THREAD

**Issue by pinterface** [alistapart/AListApart#383]
<link> tags currently list two feed URLs: `/site/rss`, which happily redirects to feedburner; and `/site/abridged-rss`, which at one point used to work, but is at present a 404.

```html
<link rel="alternate" type="application/rss+xml" title="A List Apart: The Full Feed" href="/site/rss" />
<link rel="alternate" type="application/rss+xml" title="A List Apart: The Abridged Feed (just articles and columns)" href="/site/abridged-rss" />
```

The RSS page (/about/rss), meanwhile, suggests `/main/feed` for the RSS URL.

Makes it a bit confusing to know which URL to subscribe to.

**Comment by michellekondou** [comment]
That was an oversight and it has now been corrected - thank you @pinterface for letting us know! 
The correct feed URL is /main/feed.
