### ISSUE TITLE
AListApart API

### ISSUE THREAD

**Issue by 108kb** [alistapart/AListApart#389]
Hi @alistapart,

do you have any API for your website instead of RSS?

Thank you before.

**Comment by murtaugh** [comment]
We do not. What sort of thing are you looking for?

**Comment by farizdev** [comment]
May I make a android application version for alistapart?

**Comment by FilipNest** [comment]
I've built JSON REST APIs on top of ExpressionEngine before so if this is something other people are interested in I'd happily volunteer some time to contribute it. I'm guessing read only with search / filtering? Might be too niche but if wanted I can try.
