### ISSUE TITLE
Comment # listing incorrectly includes deleted comments

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#390]
In the admin, I closed two spam comments in alistapart.com/article/the-coming-revolution-in-email-design. Before I did so, there had been 7 comments visible on the page (2 of them spam). After I closed the 2 spam comments, only 5 comments were visible. That is good and expected. 

BUT the page still proudly tells readers that there are 7 comments. 

It counts closed comments includes them in its display to users. It should not do that. 

![img_2998](https://cloud.githubusercontent.com/assets/2983799/20451929/87108b7e-adcd-11e6-953c-7f144158ddd2.PNG)

**Comment by murtaugh** [comment]
The cache just needed to clear.
