### ISSUE TITLE
Our RSS shows the 404 animation instead of the sponsor message

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#391]
![img_9477](https://cloud.githubusercontent.com/assets/2983799/20931082/e9cd22c6-bb9d-11e6-83b4-c7ec222cd9d4.PNG)

**Comment by michellekondou** [comment]
The http:// prefix was missing from the two latest sponsor articles, I just went in and fixed it!

**Comment by zeldman** [comment]
Thank you.
