### ISSUE TITLE
Contact Saul Carlin with concerns

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#392]

**Comment by murtaugh** [comment]
?

Don’t understand this issue.

**Comment by zeldman** [comment]
An old to-do that got Zap'd into a GitHub Issue. Presumably as part of the testing that occurs while building a Zap. Never fear. Now that the Zap has been created, Zapier will only generate a new Issue when a *new* BC3 To-Do is posted to Alistapart.
