### ISSUE TITLE
Images in page How We Hold Our Gadgets are not being rendered

### ISSUE THREAD

**Issue by code-warrior** [alistapart/AListApart#394]
The 11 images used at the **How We Hold Our Gadgets** page ([`https://alistapart.com/article/how-we-hold-our-gadgets`](https://alistapart.com/article/how-we-hold-our-gadgets)) are not rendering because they’re being served over `http` not `https`.

![screenshot 2017-02-24 16 18 05](https://cloud.githubusercontent.com/assets/1843562/23321476/b923487c-faad-11e6-8813-28d30ccebfd4.png)

**Comment by murtaugh** [comment]
We've only recently switched over to https, and we're still updating content.

Thanks for the report — I've updated this one, its cache should clear soon.
