### ISSUE TITLE
Website title is overlapped by navbar on PC Windows 8.1 Chrome

### ISSUE THREAD

**Issue by adam-arold** [alistapart/AListApart#395]
Please see attached screenshot. I use 1920*1080 resolution.

![listapart](https://cloud.githubusercontent.com/assets/1253248/23342507/289e404e-fc5c-11e6-9737-01774a249238.png)

**Comment by zeldman** [comment]
It's designed that way. :)



…………………………………

studio.zeldman <http://studio.zeldman.com>
148 Madison Avenue, Suite 600
New York, NY 10016
917-746-4838

An Event Apart <http://aneventapart.com/subscribe> | A List Apart
<http://alistapart.com/> | A Book Apart <https://abookapart.com>
Big Web Show
<https://itunes.apple.com/us/podcast/the-big-web-show/id370445683?mt=2> |
zeldman.com | @zeldman <https://twitter.com/zeldman>
