### ISSUE TITLE
Masthead hanging; Cloudflare stuck?

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#396]
Morning!

I updated Mica’s title to editor-in-chief  on our masthead page over 30 minutes ago in EE, but the darned page still says “Managing editor.”

https://alistapart.com/about/masthead

I assume this is a Cloudflare caching issue, but can you verify? or, even better, clear the cache?

Also: jeez! Over 30 minutes and the cache still hasn’t cleared. I’m kind of hating Cloudflare these days.

z

**Comment by awkawk** [comment]
Says Editor in Chief for me

**Comment by michellekondou** [comment]
@zeldman I cleared the cache - mind you the cache is purged every 8 hours - when you made the update to the entry  though it should have updated, I need to revisit the Cloudflare Module after https.

**Comment by zeldman** [comment]
Thank you both, @michellekondou and @awkawk ! 👍
