### ISSUE TITLE
Please remove the JOB BOARD from A List Apart

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#398]
We were unable to reach an accommodation with the new owners of the Job Board. Please remove the Job Board from A List Apart. (Be sure to remove from all templates in which it appears.)

We will find other ways to

**Comment by michellekondou** [comment]
Removed!

**Comment by zeldman** [comment]
Awesome, @michellekondou.

@mikepick, with the job board removed, the front page looks unbalanced below the HR (in the section marked "More From A List Apart." See screenshot. Anything we can quickly do about that?

![image](https://cloud.githubusercontent.com/assets/2983799/25949820/d8b464c8-3626-11e7-8bf0-68a14286d37c.png)

**Comment by michellekondou** [comment]
By the way, this is what I'm seing
![morefromala](https://cloud.githubusercontent.com/assets/1759784/25949957/01366e10-3662-11e7-9c3d-b8e784685ffe.png)

**Comment by zeldman** [comment]
D’oh! You’re right, Michelle. 

I saw nothing in the right column on Chrome because I have anti-tracking and content-blocking plug-ins that evidently detect the scripts BuySellAds uses to track even our house ads. (Nothing malicious there; as part of their service, they run scripts on any ad they serve—even “home” ads like ours, which are currently served to our site via BSA.)

So—never mind. Let’s close this again. We’re done here.

(BTW, in Safari, where I have fewer content blockers, I see this:)

![safarisnaps001](https://cloud.githubusercontent.com/assets/2983799/25950516/36b13978-3629-11e7-898f-abcaea3e52f3.png)
