### ISSUE TITLE
Pantheon ad should not be appearing in general pages

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#402]
Pantheon ad is showing up in article pages and elsewhere. See screenshot. It should ONLY show up on the event pages of the events Pantheon has sponsored this year.

![google chromescreensnapz001](https://user-images.githubusercontent.com/2983799/28279254-eca0ac02-6aed-11e7-9529-2cc29ad66d9f.png)

**Comment by zeldman** [comment]
Unsolved after nearly a month. Critical. @michellekondou

**Comment by michellekondou** [comment]
@zeldman, those ads are coming in from BuySellAds, shall I contact them? 
Also I have to note, I do not see any ads because I am in Greece and ads are not turned on for Greece via the BuySellAds package. I only get the default A Book Apart ad.

**Comment by zeldman** [comment]
First of all, I had no idea you could not see the ads. Thank you for letting me know. Do you not see them even on the dev server? Crazy.

> _shall I contact them? Or do I just remove the BuySellAds tags altogether?_

Great question. We are going to stop running BuySellAds because they are not paying us anything (this is why we have no money to pay anyone's salary). Maybe we just need to shut off their ads altogether by removing the ad code from the templates. I will let them know today, and ask what day we can remove them. And then I will let you know.

The much worse problem than running an unpaid Pantheon ad in places where Pantheon never paid for it is the problem where a huge ad sits on top of the copy, blocking it, which makes the magazine unreadable. I posted about it in a different thread but will share a screenshot here as well. 

![google chromescreensnapz002](https://user-images.githubusercontent.com/2983799/29463364-6b07a8fe-8400-11e7-9b28-cdc8eb5a3520.png)
