### ISSUE TITLE
Use cssnano in build?

### ISSUE THREAD

**Issue by malchata** [alistapart/AListApart#403]
There's a PostCSS plugin for slimming down CSS called [cssnano](http://cssnano.co). It doesn't appear to be used in this repo in the gulp build process, but it could help shave a few KBs off and help things render a touch faster. If there's interest, I'd like to investigate.

**Comment by zeldman** [comment]
+1

cc: @michellekondou

**Comment by malchata** [comment]
cssnano seems to shave 2.6 KB from `styles.css`. Not much, but worth considering since the effort to implement was so low. There are many other stylesheets in the `css` folder that may benefit (unless they're already part of `styles.css`).
