### ISSUE TITLE
A List Apart RSS feed broken

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#404]
A List Apart's main feed is broken:

https://alistapart.com/main/feed

Error message: “This XML file does not appear to have any style information associated with it. The document tree is shown below.”

Hootsuite Publisher is suddenly unable to generate Twitter and Facebook feeds from A List Apart's full feed because it contains no data.

(https://hootsuite.com/dashboard#/publisher)

![google chromescreensnapz003](https://user-images.githubusercontent.com/2983799/28980884-7b188b8e-791d-11e7-90c0-92e969257d30.png)

**Comment by zeldman** [comment]
@michellekondou , any word on this?

**Comment by michellekondou** [comment]
Hi  @zeldman I see the feed is not broken, I assume it was a temporary issue, shall I close this?
