### ISSUE TITLE
Unable to update author bio

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#405]
Hi, Michelle. Brandon Gregory joined us as a tech editor and asked me to update his bio page to include his Twitter handle. I've added the Twitter handle to his member page profile both as a handle in the Twitter field; a full https URL in the Twitter field; and a link in the body of his bio text, in a new sentence I wrote specifically so I could insert his Twitter bio there (since the Twitter data entry field wasn’t working). Nothing ever changed, no matter how many ways I tried to make this very simple update.

You may suggest that the changes *were* being made, but were being hidden from me because of Cloudflare caching. I thought that, too, so I emptied the Cloudflare cache.

I deleted just the specific bio page I was working on from the cache. When that had zero effect, I deleted the entire site cache. That also had no effect. (I mean, I guess it temporarily made the whole site slower, but it still did not show any of the updates I had made to the author page.)

Please see all three screenshots, below, which make the problem crystal-clear.

I'm puzzled. And, after 20 minutes of trying to make a 2-minute update, I'm out of ideas. What's wrong? Any ideas? Thanks.

![google chromescreensnapz001](https://user-images.githubusercontent.com/2983799/29146840-76e75ee2-7d31-11e7-9f3a-9b8b47051906.png)

![google chromescreensnapz002](https://user-images.githubusercontent.com/2983799/29146843-79b71a2c-7d31-11e7-996b-656d514a96c5.png)

![google chromescreensnapz003](https://user-images.githubusercontent.com/2983799/29146846-7d6837c8-7d31-11e7-81c1-850579ee3ffb.png)

**Comment by murtaugh** [comment]
A while ago we created a Contributors channel that manages what’s displayed on bio pages, so you need to edit his entry in that channel, and not his member account info.

**Comment by zeldman** [comment]
@murtaugh 

I cannot find the Contributors channel in EE. 

- It doesn't appear to be in Members: Member Groups.
- There is a *listing* for a Contributors Channel in Admin: Channel Administration: Channels: ( https://alistapart.com/geocities/index.php?/cp/admin_content/channel_management ) but the links there are strictly for high-level Admin tasks I have no intention of touching (e.g. Edit Preferences, Edit Group Assignments, and Delete). 
- It’s not in the Edit Profile dialog https://user-images.githubusercontent.com/2983799/29146840-76e75ee2-7d31-11e7-9f3a-9b8b47051906.png

I found Jimmy Hoffa in there, but cannot find a Contributors Channel. Can you kindly let me know where it is? (URL & screenshot would help.) Thanks!

z

**Comment by murtaugh** [comment]
<img width="509" alt="screen shot 2017-08-10 at 12 27 40 pm" src="https://user-images.githubusercontent.com/308752/29180943-617f9178-7dc7-11e7-8f9f-ce0d1f0d4282.png">

**Comment by zeldman** [comment]
Thanks, @murtaugh !

**Comment by zeldman** [comment]
@murtaugh 

And de saga continue!

- Edited Contributors file.
- Change did not show up.
- Purged site-wide cache.
- Change still did not show up. 

Thoughts?

**Comment by murtaugh** [comment]
FWIW, It’s much better to *not* do a site wide purge, and only purge individual URLs. Even if it seems like it's taking longer than it should, purging the entire cache costs us speed benefits for every URL for the sake of fixing one.

I'm no longer sure what the timeline of events here is, but I cleared the cache for the single file (through CloudFlare, not EE's dashboard), and I saw a link — but the link didn't work because a whole URL was in his entry. I updated his entry, purged the cache for the single URL again, and it seems to be correct now.

For the future, there’s a form where users can update their own profile; it’s linked in the footer when you’re logged in. @michelle, I notice that field doesn’t note that it only wants the twitter handle, so some folks might be inserting the entire URL.

**Comment by zeldman** [comment]
> _the link didn't work because a whole URL was in his entry._ 

Right. In my previous four attempts, I had tried it both ways before giving up. The UI doesn't say "@ only" or "Full URL, please" so I guessed. I actually guessed @handle-only first, but when nothing changed, I switched to the full URL. When that still did not change, I gave up. Thanks for bearing with me on this.

> _For the future, there’s a form where users can update their own profile; it’s linked in the footer when you’re logged in._

That's great to know. Thanks.

> _FWIW, It’s much better to not do a site wide purge_

I know, which is why I tried the single-page-purge first. But, you know, like I said, nothing was working, so I tried everything.

**Comment by brandongregory** [comment]
FYI, I'm not getting the link to update my profile, even after logging in. I'm just seeing the log in link every time.

**Comment by brandongregory** [comment]
Actually, after clicking around on the site, it started showing up. But it's the user profile, not the contributor profile.

**Comment by zeldman** [comment]
@murtaugh ? Any thoughts? 

@brandongregory said:

> _I'm not getting the link to update my profile, even after logging in. I'm just seeing the log in link every time. ...  Actually, after clicking around on the site, it started showing up. But it's the user profile, not the contributor profile._

**Comment by murtaugh** [comment]
Huh — I guess you don't see the full set of fields if you're an author, which I don't think is what we intended. Anyway, you should see the whole set of fields now.

**Comment by zeldman** [comment]
@murtaugh – Thank you, Tim! :)

**Comment by m1ca** [comment]
We do NOT want to enable authors/contributors to edit their own bios.

**Comment by zeldman** [comment]
@murtaugh said:

> For the future, there’s a form where users can update their own profile; it’s linked in the footer when you’re logged in. @michelle, I notice that field doesn’t note that it only wants the twitter handle, so some folks might be inserting the entire URL.

@m1ca said:

> We do NOT want to enable authors/contributors to edit their own bios.

So, are we good? (Since, apparently, they can’t?)

**Comment by zeldman** [comment]
@m1ca @murtaugh @mikepick 

We are still having problems getting a bio of ALA event sponsor (and Mike and Tim’s current client) Roger Black's bio to show up on alistapart.com. 

Please see this thread and help!

https://3.basecamp.com/3466293/buckets/4293923/messages/632181117

* I created a bio for Roger but it will not show up on alistapart.com. Followed all instructions, no luck. 

The event was supposed to go live today, but nobody who knows how to do so has produced it, and nobody has responded to the weird difficulty we’re having getting bios to show up on the site.

**Comment by zeldman** [comment]
@mikepick I sent you an invitation to the Basecamp in question. Thanks.

**Comment by zeldman** [comment]
@erinlynch Maybe you can help? I'll send you an invitation to the Basecamp thread...

**Comment by murtaugh** [comment]
I can’t see the Basecamp thread, but I can see Roger’s bio on the site:

https://alistapart.com/author/roger-black

**Comment by zeldman** [comment]
Oh, sweet Jesus. Thank you.

So what we have learned is, a newly created bio page does not show up for at least 8 hours, even after a cache flush. 

Because Cloudflare and ExpressionEngine.

So now I will create Jen Simmons's bio, so we can take the event live in 48 hours, after her bio appears.

Thanks, @murtaugh

**Comment by zeldman** [comment]
Apparently @m1ca fixed it.

Thanks, @murtaugh .

**Comment by zeldman** [comment]
Fixed. I’m not even going to explain this one.
