### ISSUE TITLE
Please make Brandon Gregory a CMS Admin

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#406]
Hi, @michellekondou !

Brandon Gregory is helping with content production. Please make Brandon an Admin of the A List Apart CMS. 

And while you’re doing so, please take screenshots and share instructions so I know how to do this in the future without bothering you! Thanks!

Brandon’s member number is 148385; his email is brandon.gregory.1981@gmail.com; his screen name is Brandon Gregory; and his user name is brandongregory. https://alistapart.com/geocities/index.php?S=0&D=cp&C=myaccount&id=148385

**Comment by zeldman** [comment]
@murtaugh 

Sorry to disturb, I know you’re not active here any more, but @michellekondou ’s on vacation ’til the 15th, and I was wondering if you could tell me how to do this, so I can take care of it myself. Thanks!

z

**Comment by murtaugh** [comment]
No problem, happy to help.

I’ve just made Brandon a Super Admin; someone should show him the ropes before letting him loose in EE :)

**Comment by zeldman** [comment]
Hey, @murtaugh !

> _I’ve just made Brandon a Super Admin_

Thank you very, very much.

> _someone should show him the ropes before letting him loose in EE :)_

Absolutely. Brandon and I will start discussing ALA EE basics tomorrow via Hangout, which will be enough to get him started following the ALA Technical Style Guide and marking up articles.

By the way, is there anything in the ALA Technical Style Guide that strikes you as obsolete or in need of an update? https://alistapart.com/about/ala-technical-style-guide

(I’m going to ask @iamjolly to check it for the latest WCAG recommendations as well.)

**Comment by michellekondou** [comment]
@zeldman  closing this!
