### ISSUE TITLE
Book link on Cennydd Bowles bio goes to toilet page. 

### ISSUE THREAD

**Issue by fellene** [alistapart/AListApart#421]
https://alistapart.com/author/cbowles
In reviewing the page for Cennydd, I clicked on a link for his book and it goes to a toilet sales page. 
http://undercoverux.com/ 

I do not see anything related to UX there. His real book seems to be  at https://www.amazon.com/Undercover-Experience-Design-Voices-Matter/dp/0321719905/ref=sr_1_fkmr0_1?ie=UTF8&qid=1538071080&sr=8-1-fkmr0&keywords=Undercover+UX+Design

Looks like the domain expired and was hijacked. I hate it when that happens. You might want to clear that up.

**Comment by zeldman** [comment]
Oh, dear. Thank you, @fellene. We will attend to it.

:)

**Comment by zeldman** [comment]
Fixed! Thanks again.  :)

**Comment by fellene** [comment]
Whew! Thanks. He’s speaking at CHIFOO next week and I was trying to find his first book. .- f
