### ISSUE TITLE
Wrong Images Shown on Article

### ISSUE THREAD

**Issue by garrettdimon** [alistapart/AListApart#430]
It looks like my article somehow ended up with the wrong images. A quick search didn't turn them up for me locally, but if they've disappeared, I might be able to find them.
https://alistapart.com/article/your-emails-and-recipients-deserve-better-context/

**Comment by gangeez18** [comment]
this article is so good.We are a [web & app](http://gangeez.in/) development company that turns your ideas into a new driving force of your business with our valuable product like.
http://gangeez.in/
