### ISSUE TITLE
Admin nav box taking up space?

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#47]
Why would a fixed position div be taking up vertical space?

As an admin user, view this page logged out, and then logged in:

http://alistapart.com/columns

The content below the logo shifts.

**Comment by michellekondou** [comment]
@murtaugh I don't see any difference, in which browser and under what circumstance do you see the bug?

**Comment by murtaugh** [comment]
Yeah, I can't reproduce it either. Magic!
