### ISSUE TITLE
Comments timing out?

### ISSUE THREAD

**Issue by Wilto** [alistapart/AListApart#5]
Over a certain threshold, comments won’t load.

See: http://alistapart.com/comments/flashsatay

**Comment by murtaugh** [comment]
@michellekondou: If I understood you in Slack, you said you think this is related to code snippets in the article? If that were the case, the two comment-specific URLs should load, but they don't.

http://alistapart.com/comments/embed-comments/flashsatay (called via ajax after the article page loads)
http://alistapart.com/comments/flashsatay (permalink for comments for SEO and non-JS users)

**Comment by michellekondou** [comment]
It was related to code snippets in the comments. We have to check what gets sanitized. The comments are loading now so I'm closing this.
