### ISSUE TITLE
Validation on Sign in/sign up comments form

### ISSUE THREAD

**Issue by cfarm** [alistapart/AListApart#78]
The sign in/signup form for the comments on blog posts does not throw an error in the page, it redirects you to an unstyled page with the error.

Context: trying to sign up as a new user to comment on a blog post

Issue: error message was that the username I chose was already in use. 

Expected behavior: error is shown inline in the form on the blog post page, rather than on a new (unstyled) page.

![screenshot 2014-03-12 13 58 59](https://f.cloud.github.com/assets/702526/2401015/ca1eeece-aa10-11e3-82e1-f809079fbb77.png)

**Comment by michellekondou** [comment]
I have moved this to the dark corners repo.
