### ISSUE TITLE
Inlining CSS

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#93]
I don't think the `{path}` variable does what you want it to — it's one of EE features that, IMHO, tries to be more clever than it needs to be. My affection for EE increased exponentially when I figured out I could ignore it completely.

A couple ideas, some of them obvious, but I’m not sure what you’ve tried so far.

1. Can you write the files wherever you want? If so, we should try turning the file into a global variable, by writing it here:

```
/d/_repo/global_variables/default_site/critical-article-css.glob
```

If that doesn't work, we can try making it a snippet (`/d/_repo/snippets/critical-article-css.snip`), or, last resort, an embedded template (`/d/_repo/default_site/embeds.group/critical-article-css.html`).

2. If none of that works, we can look into using PHP to include the file, but it would have to be done on a case-by-case basis depending on whether the template in question already use PHP (and how it uses it).

**Comment by michellekondou** [comment]
Should this be closed? /cc @murtaugh
